define([], function () {
  return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",

    //Digital Badge"
    "DigitalBadgePageTitle": "Digital Badge",
    "LoadingSpinnerLabel": "Loading...",
    "DigitalBadgeAppBannerAltText": "Microsoft team members engaging in a discussion",
    "PreAcceptPageTitle": "Claim your digital badge!",
    "PreAcceptDisclaimer": "<span style='font-weight:bold;'>Welcome to the digital badge utility</span> <br/><br/> <span>As part of your membership to the Champions Program, you have earned a digital badge! This utility will enable you to '<em>claim</em>' your digital badge by overlaying it on top of your existing profile picture. <br/><br/> Please note that this will update your profile picture across all of Microsoft 365 (Exchange, Teams, SharePoint, etc).</span>",
    "PreAcceptDisclaimer2": "If desired, <span style='font-weight:bold;'>you will have an opportunity to 'save' a copy of your existing profile picture</span> without the digital badge overlay in the succeeding steps. Please click ‘Accept’ to continue (you might see a pop-up open and prompt for sign-in).",
    "NotQualifiedPreAcceptDisclaimer": "<span style='font-weight:bold;'>Welcome to the digital badge utility</span>. As part of your membership of the Champions Program, you can earn a digital badge! This utility will enable you to '<em>claim</em>' your digital badge by overlaying it on top of your existing profile picture. Please note that this will update your profile picture across all of Microsoft 365 (Exchange, Teams, SharePoint, etc.)",
    "HowtoGetDigitalBadgeText": "How to get Champion Badge",
    "MultipleBadgeMessage": "Select a badge from the below list. Selected badge will be applied on your profile picture.",
    "NoBadgeMessage": "No badges found for you to select. Please check with your App Administrator.",
    "DigitalBadgeSubPageTitle": "Here's how your digital badge will look!",
    "ProfileImageAlt": "My profile image used across O365, Teams, etc",
    "BadgeImageAlt": "Medal-shaped award with the letter C in the middle signifying I am a part of the Champions Program",
    "NoProfileImageAlt": "Silhouette of a person, signifying no profile image is currently applied to your account",
    "ApplyButtonText": "Apply image",
    "ApplyButtonAriaDescription": "By clicking this button you're giving the Champions Program web part permission to update your profile picture on your behalf.",
    "ApplyButton": "Apply",
    "DownloadButtonText": "Download",
    "DownloadButtonAriaDescription": "Click to download your current profile image",
    "DownloadingButtonText": "Downloading...",
    "DownloadedButtonText": "Downloaded",
    "DownloadedButtonSecondaryText": "Your downloaded profile image can be found in your device's Downloads folder.",
    "DownloadButtonSecondaryText": "Download your current profile image",
    "PreApplyDisclaimer": "This is a preview of your new profile picture including the digital badge. If you wish to download your existing profile picture prior to applying the digital badge, click on the '<strong>Download your current profile image</strong>' link.<br />",
    "PreApplyDisclaimer1": "<br />Clicking 'Apply Image' will update your Microsoft 365 profile picture with this new image. <strong>Please note this will update your profile picture across all of Microsoft 365 and cannot be reverted through this page</strong>. <br/><br/>If you'd like to change your picture back, you can use the <a class='constAnchor' href='https://outlook.office365.com/owa/' target='_blank' aria-label='Open the Outlook web application in a new browser tab or window'>Outlook web application</a>.",
    "NoProfileImageDescription": "If you have already associated a picture with your profile, and you’re still seeing this message, your picture might not be available yet. Please try again later, or contact the <a class='constAnchor' href='https://microsoft.service-now.com/' target='_blank' aria-description='Open the Outlook web application in a new browser tab or window'>helpdesk</a> if it still doesn’t show up after 24 hours.",
    "AcceptButtonText": "Accept",
    "AcceptButtonAriaDescription": "By clicking this button you're giving the Champions Program web part permission to update your profile picture on your behalf.",
    "UnauthorizedText": "You are not qualified for Champion Badge Program at this time",
    "ApplySpinnerLabel": "Applying new profile image to your account...",
    "DigitalBadgeSuccessMessage": "<strong>Congratulations!</strong> You have successfully claimed your digital badge and your profile picture has been updated. Please allow up to 24 hours to see the update reflected across all Microsoft 365 applications (including Teams).",
    "DigitalMembersToolTip": "Get your digital badge and apply it to your profile image",
    "DigitalBadgeLabel": "Digital Badge",
    "AdminToolsLabel": "Admin Tools",

    //Header
    "AppHeaderTitleLabel": "Tournament of Teams",
    "AppLogoToolTip": "Home",
    "MoreInfoToolTip": "More Info",
    "SupportToolTip": "Support",
    "FeedbackToolTip": "Feedback",
    "WelcomeLabel": "Welcome",

    //More Info Icon Content
    "AboutHeaderLabel": "About Tournament of Teams:",
    "AboutContentLabel": "Tournament of Teams enables the entire organization the gamification and learning experiences of bringing adoption themed tournaments for driving healthy usage. Within the platform you can create and deliver tournaments to help drive healthy usage of scenarios, inspire users by running campaigns prompting new learnings, and track and record tournament actions for post event recognition and impact.",
    "AdditionalResourcesHeaderLabel": "Additional Resources:",
    "AdditionalResourcesContentLabel": "The Microsoft Teams Customer Advocacy Group is focused on delivering solutions like these to inspire and help you achieve your goals. Follow and join in through these other resources to learn more from us and the community:",
    "M365ChampionCommunityLinkLabel": "Microsoft 365 Champion Community",
    "DrivingAdoptionLinkLabel": "Driving Adoption on the Microsoft Technical Community",
    "CurrentVersionLabel": "Current Version:",
    "LatestVersionLabel": "Latest Version:",
    "TOTGitHubLinkLabel": "GitHub",
    "VisitLabel": "Visit the Tournament of Teams pages to learn more:",
    "OverviewLabel": "Overview & Information on our",
    "MSAdoptionHubLinkLabel": "Microsoft Adoption Hub",
    "DocumentationLabel": "Solution technical documentation and architectural overview on",


    //-------------------------------------TOT-------------------------------------------------
    // Common
    "SaveButton": "Save",
    "BackButton": "Back",
    "EnableTOTToolTip": "Enable Tournament of Teams",
    "EnableTOTLabel": "Enable Tournament of Teams",


    // Create Tournament
    "CreateTournamentPageTitle": "Create Tournament",
    "CreateTournamentSuccessLabel": "Tournament created successfully.",
    "TournamentNameLabel": "Tournament Name",
    "TournamentNameErrorLabel": "Tournament Name is required.",
    "TournamentDescriptionLabel": "Tournament Description",
    "TournamentDescPlaceHolderLabel": "Tournament Description(Max 500 characters)",
    "SelectTeamsActionsLabel": "Select Teams Actions:",
    "TeamsActionInfoToolTip": "Select from the below available Teams actions to include in the new tournament. To add new tournament actions to choose from, visit the Manage Tournament Actions from the Admin Tools.",
    "ActionErrorLabel": "Select atleast one action to create a tournament.",
    "CreateTournamentButton": "Create Tournament",
    "DuplicateTournamentNameError": "Tournament name already exists. Enter another name for tournament.",



    //TOT Common    
    "TOTBreadcrumbLabel": "Tournament of Teams",

    //TOT Landing
    "EnableTOTSuccessMessage": "Tournament of Teams enabled successfully. Please refresh the app before using.",
    "TOTLeaderBoardPageTitle": "Leader Board",
    "TOTMyDashboardPageTitle": "My Dashboard",
    "ManageTournamentActionsToolTip": "Accessing Tournament Actions List",
    "ManageTournamentActionsLabel": "Manage Tournament Actions",
    "ManageTournamentsLabel": "Manage Tournaments",
    "ManageAdminsToolTip": "Accessing Admin List",
    "ManageAdminsLabel": "Manage Admins",
    "ManageDigitalBadgesLabel": "Manage Digital Badges",
    "QuickLinksLabel": "Quick Links",

    //Enable Tournament
    "ManageTournamentsPageTitle": "Manage Tournaments",
    "ManageToTLabel1": "Multiple tournaments can be started at a time. See below for the current active tournaments, ability to complete the tournament, as well as the ability to start a new tournament.",
    "ManageToTLabel2": "Once a tournament has been started and completed it will not be available to start again; however, you can create a new tournament using the same actions if you would like to complete a similar tournament!",
    "EndTournamentDialogMessage": "Are you sure want to complete the tournament?",
    "StartTournamentDialogMessage": "Are you sure want to start the new tournament?",
    "ConfirmLabel": "Confirm",
    "YesButton": "Yes",
    "NoButton": "No",
    "ActiveTournamentLabel": "Active Tournaments",
    "EndTournamentButton": "Complete Tournament",
    "StartTournamentHeaderLabel": "Start Tournament",
    "NoTournamentMessage": "No tournaments found.",
    "SelectTournamentMessage": "Select a tournament to start.",
    "NoActiveTournamentMessage": "No active tournaments found.",
    "SelectEndTournamentMessage": "Select a tournament to complete.",
    "StartTournamentButton": "Start Tournament",
    "EndTournamentSuccessMessage": "Tournament completed successfully.",
    "EnableTournamentSuccessMessage": "Tournament started successfully.",
    "CompleteTournamentSpinnerMessage": "Completing Tournament...",

    //TOT Leaderboard & TOT My Dashboard
    "NoActiveParticipantsMessage": "There are no active participants at the moment. Be the first to participate and log an activity from My Dashboard!",
    "NoActiveTournamentMessage": "There is no active tournament at the moment. Please check back later.",
    "TournamentLabel": "Tournament",
    "DescriptionLabel": "Description",
    "NoActiveParticipantsErrorMessage": "There are no active participants at the moment. Be the first to participate and log an activity from ",
    "PendingActionsLabel": "Pending Actions",
    "PendingActionsSuccessMessage": "There are no more pending actions in this tournament.",
    "SelectActionsErrorMessage": "Select atleast one action to proceed.",
    "FormSavingMessage": "Saving your details....",
    "CompletedActionsLabel": "Completed Actions",
    "RankLabel": "Rank",
    "UserLabel": "User",
    "MyDashboardInfoIconMessage": "Find out more about this action",
    "SelectTournamentPlaceHolder": "Select Tournament",
    "MyTournamentsLabel": "My Tournaments",
    "OrLabel": "OR",
    "MyTournamentsTooltip": "Active tournaments that you have participated in already",

    //TOT SideBar
    "PointsLabel": "Points",
    "TournamentRankLabel": "Tournament Rank",
    "ParticipantsLabel": "Participants",

    //TOT Report
    "TournamentReportsPageTitle": "Tournaments Report",
    "TotalActivitiesLabel": "Total Activities",
    "TotalPointsLabel": "Total Points",
    "TotalParticipantsLabel": "Total Participants",
    "TotalPercentageCompletionLabel": "% of Total Completion",
    "Top5ParticipantswithPointsLabel": "Top 5 Participants with Points",
    "Top5TournamentswithParticipantsLabel": "Top 5 Tournaments with Participants",
    "ParticipantsStatusLabel": "Participants Status",
    "ParticipantsDetailsLabel": "Participants Details",
    "NameLabel": "Name",
    "PercentageTournamentCompletedLabel": "% Tournament Completed",
    "ActivitiesCompletedLabel": "Activities Completed",
    "NoRecordsinGridLabel": "No Records found!",
    "SearchPlaceholder": "Search by Participant's Name",
    "NoCompletedTournamentsMessage": "There is no completed tournament at the moment. Please check back later.",
    "ReportsDropdownInfoIconText":"Report can be generated only for completed tournaments.",
    "RefreshIconInfoText": "Click refresh to see latest data",

    //Provisioning
    "ProvisioningErrorMessage" : 'An issue has occured during the app setup. Please try setting up the app again.',
    "ProvisioningSuccessMessage" : 'Tournament of Teams has been deployed successfully. Please refresh the app to continue.',
    "SpinnerMessage" : "Setting up the App.....",
    "ProvisioningSetupMessage" : "This process will take a few moments to complete. Please do not navigate away until you see the completed successfully message."
  }
});