define([], function () {
    return {
        "PropertyPaneDescription": "Descripción",
        "BasicGroupName": "Nombre de grupo",
        "DescriptionFieldLabel": "Campo Descripción",
        "DigitalBadgePageTitle": "Insignia digital",
        "LoadingSpinnerLabel": "Cargando...",
        "DigitalBadgeAppBannerAltText": "Los miembros del equipo de Microsoft participan en una discusión",
        "PreAcceptPageTitle": "Reclama tu distintivo digital.",
        "PreAcceptDisclaimer": "<span style='font-weight:bold;'>Te damos la bienvenida a la utilidad de distintivo digital</span> <br/><br/> <span>Como parte de tu suscripción al Programa De Expertos, has ganado un distintivo digital. Esta utilidad te permitirá \"<em>reclamar</em>\" el distintivo digital superponiéndolo sobre la imagen de perfil existente. <br/><br/> Ten en cuenta que se actualizará la imagen de perfil en todo Microsoft 365 (Exchange, Teams, SharePoint, etc.).</span>",
        "PreAcceptDisclaimer2": "Si lo deseas, <span style='font-weight:bold;'>tendrás la oportunidad de \"guardar\" una copia de la imagen de perfil existente</span> sin la superposición de la insignia digital en los pasos siguientes. Haga clic en \"Aceptar\" para continuar (es posible que se abra una ventana emergente que le pida que inicie sesión).",
        "NotQualifiedPreAcceptDisclaimer": "<span style='font-weight:bold;'>Te damos la bienvenida a la utilidad de distintivo digital</span>. Como parte de tu suscripción al Programa De Expertos, puedes ganar un distintivo digital. Esta utilidad te permitirá \"<em>reclamar</em>\" el distintivo digital superponiéndolo sobre la imagen de perfil existente. Ten en cuenta que se actualizará la imagen de perfil en todo Microsoft 365 (Exchange, Teams, SharePoint, etc.).",
        "HowtoGetDigitalBadgeText": "Cómo obtener la insignia de Campeón",
        "MultipleBadgeMessage": "Seleccione un distintivo de la lista siguiente. El distintivo seleccionado se aplicará a la imagen de perfil.",
        "NoBadgeMessage": "No se encontraron insignias para seleccionar. Compruébalo con el administrador de la aplicación.",
        "DigitalBadgeSubPageTitle": "Este es el aspecto que tendrá tu insignia digital.",
        "ProfileImageAlt": "Mi imagen de perfil usada en O365, Teams, etc.",
        "BadgeImageAlt": "Premio en forma de medalla con la letra C en el medio que significa que forme parte del Programa De Expertos",
        "NoProfileImageAlt": "Silueta de una persona, que indica que no hay ninguna imagen de perfil aplicada actualmente a tu cuenta",
        "ApplyButtonText": "Aplicar imagen",
        "ApplyButtonAriaDescription": "Al hacer clic en este botón, concederás permiso al elemento web del Programa de campeones para actualizar la imagen de perfil en tu nombre.",
        "ApplyButton": "Aplicar",
        "DownloadButtonText": "Descargar",
        "DownloadButtonAriaDescription": "Haz clic para descargar la imagen de perfil actual",
        "DownloadingButtonText": "Descargando...",
        "DownloadedButtonText": "Descargado",
        "DownloadedButtonSecondaryText": "La imagen de perfil descargada se encuentra en la carpeta Descargas del dispositivo.",
        "DownloadButtonSecondaryText": "Descargar la imagen de perfil actual",
        "PreApplyDisclaimer": "Esta es una vista previa de la nueva imagen de perfil, incluida la insignia digital. Si deseas descargar la imagen de perfil existente antes de aplicar la insignia digital, haz clic en el vínculo \"'<strong>Descargar la imagen de perfil actual\"</strong>.<br />",
        "PreApplyDisclaimer1": "<br />Al hacer clic en \"Aplicar imagen\", se actualizará la imagen de perfil de Microsoft 365 con esta nueva imagen. <strong>Ten en cuenta que se actualizará la imagen de perfil en todo Microsoft 365 y no se puede revertir a través de esta página</strong>. <br/><br/>Si quieres volver a cambiar la imagen, puedes usar la <a class='constAnchor' href='https://outlook.office365.com/owa/' target='_blank' aria-label='Open the Outlook web application in a new browser tab or window'>aplicación web de Outlook</a>.",
        "NoProfileImageDescription": "Si ya has asociado una imagen a tu perfil y sigues viendo este mensaje, es posible que la imagen aún no esté disponible. Vuelve a intentarlo más tarde o ponte en contacto con el <a class='constAnchor' href='https://microsoft.service-now.com/' target='_blank' aria-description='Open the Outlook web application in a new browser tab or window'>servicio de asistencia</a> si sigue sin aparecer después de 24 horas.",
        "AcceptButtonText": "Aceptar",
        "AcceptButtonAriaDescription": "Al hacer clic en este botón, concederás permiso al elemento web del Programa de campeones para actualizar la imagen de perfil en tu nombre.",
        "UnauthorizedText": "No está cualificado para el Programa de insignia de campeón en este momento",
        "ApplySpinnerLabel": "Aplicando la nueva imagen de perfil a su cuenta...",
        "DigitalBadgeSuccessMessage": "<strong>Enhorabuena.</strong> Has solicitado correctamente tu insignia digital y se ha actualizado tu imagen de perfil. Espera hasta 24 horas para ver la actualización reflejada en todas las aplicaciones de Microsoft 365 (incluido Teams).",
        "DigitalMembersToolTip": "Obtener la insignia digital y aplicarla a la imagen de perfil",
        "DigitalBadgeLabel": "Insignia digital",
        "AdminToolsLabel": "Herramientas de administración",
        "AppHeaderTitleLabel": "Torneo de Teams",
        "AppLogoToolTip": "Inicio",
        "MoreInfoToolTip": "Más información",
        "SupportToolTip": "Asistencia",
        "FeedbackToolTip": "Comentarios",
        "WelcomeLabel": "Bienvenido",
        "AboutHeaderLabel": "Torneo de Teams",
        "AboutContentLabel": "Tournament of Teams permite a toda la organización la gamificación y las experiencias de aprendizaje de traer torneos temáticos de adopción para impulsar un uso saludable. Dentro de la plataforma puedes crear y ofrecer torneos para ayudar a impulsar un uso correcto de los escenarios, animar a los usuarios ejecutando campañas que pidan nuevos aprendizajes y realizar un seguimiento y grabar acciones de torneo para el reconocimiento y el impacto posteriores a los eventos.",
        "AdditionalResourcesHeaderLabel": "Recursos adicionales:",
        "AdditionalResourcesContentLabel": "El grupo de atención al cliente de Microsoft Teams se centra en ofrecer soluciones como estas para inspirarte y ayudarte a alcanzar tus objetivos. Sigue y únete a estos otros recursos para obtener más información de nosotros y de la comunidad:",
        "M365ChampionCommunityLinkLabel": "Comunidad de campeones de Microsoft 365",
        "DrivingAdoptionLinkLabel": "Impulsar la adopción en Microsoft Technical Community",
        "CurrentVersionLabel": "Versión actual:",
        "LatestVersionLabel": "Versión más reciente:",
        "TOTGitHubLinkLabel": "GitHub",
        "VisitLabel": "Visite las páginas del torneo de Teams para obtener más información:",
        "OverviewLabel": "Información general e información sobre nuestro",
        "MSAdoptionHubLinkLabel": "Centro de adopción de Microsoft",
        "DocumentationLabel": "Documentación técnica de la solución e información general sobre la arquitectura en",
        "SaveButton": "Guardar",
        "BackButton": "Atrás",
        "EnableTOTToolTip": "Habilitar torneo de Teams",
        "EnableTOTLabel": "Habilitar torneo de Teams",
        "CreateTournamentPageTitle": "Crear torneo",
        "CreateTournamentSuccessLabel": "El torneo se creó correctamente.",
        "TournamentNameLabel": "Nombre del torneo",
        "TournamentNamePlaceHolderLabel": "Nombre del torneo (máximo 255 caracteres)",
        "TournamentNameErrorLabel": "Se requiere el nombre del torneo.",
        "TournamentDescriptionLabel": "Descripción del torneo",
        "TournamentDescPlaceHolderLabel": "Descripción del torneo (máximo 500 caracteres)",
        "SelectTeamsActionsLabel": "Seleccionar acciones de Teams:",
        "TeamsActionInfoToolTip": "Selecciona entre las siguientes acciones de Teams disponibles para incluirlas en el nuevo torneo. Para agregar nuevas acciones de torneo entre las que poder elegir, visita Administrar acciones del torneo desde las herramientas de Administración.",
        "ActionErrorLabel": "Selecciona al menos una acción para crear un torneo.",
        "CreateTournamentButton": "Crear torneo",
        "DuplicateTournamentNameError": "El nombre del torneo ya existe. Escribe otro nombre para el torneo.",
        "CreateTournamentsButton": "Crear torneos",
        "SingleTournamentLabel": "Torneo único",
        "MultipleTournamentLabel": "Varios torneos",
        "MultiTournamentStep": "Paso",
        "MultiTournamentStep1LinkLabel": "Descargar plantilla",
        "MultiTournamentStep1Text": " de formato de archivo de ejemplo",
        "MultiTournamentStep2": "Agrega los detalles del torneo al archivo siguiendo las directrices",
        "MultiTournamentStep3": "Cargar el archivo",
        "UploadFileButton": "Subir archivo",
        "RemoveFileLabel": "Quitar archivo",
        "ImportSpinnerMessage": "Creando torneos......",
        "ErrorMsgTournamentList": "Error al crear un elemento en la lista de torneos. Corrija los datos e inténtelo de nuevo.",
        "ErrorMsgActionsList": "Error al crear un elemento en la lista acciones. Corrija los datos e inténtelo de nuevo.",
        "ErrorMsgTournamentActionsList": "Error al crear un elemento en la lista de acciones del torneo. Corrija los datos e inténtelo de nuevo.",
        "LogMsgTournamentExists": "Omitido, porque el torneo",
        "LogMsgTournamentExists1": "ya existe.",
        "LogMsgDone": "Torneo",
        "LogMsgDone1": "Creado",
        "LogMsgInvalidTournamentName": "Omitido, ya que no tiene un nombre de torneo válido.",
        "LogMsgInvalidTemplate": "Omitido, ya que no es una plantilla válida.",
        "LogMsgMultipleTournaments": "Omitido, ya que tiene más de un nombre de torneo.",
        "LogMsgBlankSheet": "Omitido, ya que está en blanco.",
        "LogProgress": " A continuación se muestra el progreso:",
        "ImportRule1": "No modificar los encabezados de columna de la plantilla",
        "ImportRule2": "No eliminar las columnas de la plantilla",
        "ImportRule3": "Escribe los datos en todas las columnas requeridas(*) mencionadas en la plantilla.",
        "ImportRule4": "Seguir el límite de caracteres y el tipo mencionado en la plantilla para cada columna",
        "ImportRule5": "Escribe los datos de un solo torneo por cada hoja según los datos de ejemplo proporcionados",
        "ImportRule6": "Solo se pueden crear diez torneos a la vez",
        "ImportRule7": "Asegúrate de que el nombre del torneo es único",
        "TOTBreadcrumbLabel": "Torneo de Teams",
        "EnableTOTSuccessMessage": "El torneo de Teams se ha habilitado correctamente. Actualice la aplicación antes de usarla.",
        "TOTLeaderBoardPageTitle": "Panel de clasificación",
        "TOTMyDashboardPageTitle": "Mi panel",
        "ManageTournamentActionsToolTip": "Acceso a la lista de acciones del torneo",
        "ManageTournamentActionsLabel": "Administrar acciones del torneo",
        "ManageTournamentsLabel": "Administrar torneos",
        "ManageAdminsToolTip": "Acceso a la lista de administradores",
        "ManageAdminsLabel": "Administrar administradores",
        "ManageDigitalBadgesLabel": "Administrar insignias digitales",
        "QuickLinksLabel": "Enlaces rápidos",
        "ManageTournamentsPageTitle": "Administrar torneos",
        "ManageToTLabel1": "Se pueden iniciar varios torneos a la vez. Consulta a continuación los torneos que están activos, la capacidad de completar el torneo, así como la capacidad de iniciar un nuevo torneo.",
        "ManageToTLabel2": "Una vez que se haya iniciado y completado un torneo, no estará disponible para empezarlo de nuevo. Sin embargo, podrás crear un nuevo torneo con las mismas acciones si quieres completar un torneo similar.",
        "EndTournamentDialogMessage": "¿Estás seguro de que quieres completar el torneo?",
        "StartTournamentDialogMessage": "¿Estás seguro de que quieres iniciar el nuevo torneo?",
        "ConfirmLabel": "Confirmar",
        "YesButton": "Sí",
        "NoButton": "No",
        "SearchActiveTournaments": "Buscar torneos activos",
        "SearchPendingTournaments": "Buscar torneos para empezar",
        "SelectAllLabel": "Seleccionar todo",
        "NoSearchResults": "No hay resultados que coincidan con la búsqueda.",
        "ActiveTournamentLabel": "Torneos activos",
        "EndTournamentButton": "Completar torneo",
        "StartTournamentHeaderLabel": "Iniciar torneo",
        "NoTournamentMessage": "No se encontraron torneos. Vuelva a comprobarlo más tarde.",
        "SelectTournamentMessage": "Selecciona al menos un torneo para empezar.",
        "SelectEndTournamentMessage": "Selecciona un torneo para completarlo.",
        "StartTournamentButton": "Iniciar torneos",
        "EndTournamentSuccessMessage": "El torneo se completó correctamente.",
        "EnableTournamentSuccessMessage": "Los torneos se iniciaron correctamente.",
        "CompleteTournamentSpinnerMessage": "Completando torneo...",
        "EnableTournamentSpinnerMessage": "Habilitando los torneos.",
        "NoActiveParticipantsMessage": "No hay participantes activos en este momento. Sea el primero en participar y registrar una actividad desde Mi panel.",
        "NoActiveTournamentMessage": "No hay ningún torneo activo en este momento. Vuelve a comprobarlo más tarde.",
        "TournamentLabel": "Torneo",
        "DescriptionLabel": "Descripción",
        "NoActiveParticipantsErrorMessage": "No hay participantes activos en este momento. Sea el primero en participar y registrar una actividad desde ",
        "PendingActionsLabel": "Acciones pendientes",
        "PendingActionsSuccessMessage": "No hay más acciones pendientes en este torneo.",
        "SelectActionsErrorMessage": "Seleccione al menos una acción para continuar.",
        "FormSavingMessage": "Guardando los detalles...",
        "CompletedActionsLabel": "Acciones completadas",
        "RankLabel": "Clasificación",
        "UserLabel": "Usuario",
        "MyDashboardInfoIconMessage": "Más información acerca de esta acción",
        "SelectTournamentPlaceHolder": "Seleccionar torneo",
        "MyTournamentsLabel": "Mis torneos",
        "OrLabel": "O",
        "MyTournamentsTooltip": "Torneos activos en los que ya has participado",
        "PointsLabel": "Puntos",
        "TournamentRankLabel": "Clasificación del torneo",
        "ParticipantsLabel": "Participantes",
        "TournamentReportsPageTitle": "Informe de torneos",
        "TotalActivitiesLabel": "Total de actividades",
        "TotalPointsLabel": "Total de puntos",
        "TotalParticipantsLabel": "Total de participantes",
        "TotalPercentageCompletionLabel": "% de finalización total",
        "Top5ParticipantswithPointsLabel": "5 participantes principales con puntos",
        "Top5TournamentswithParticipantsLabel": "5 torneos principales con participantes",
        "ParticipantsStatusLabel": "Estado de los participantes",
        "ParticipantsDetailsLabel": "Detalles de los participantes",
        "NameLabel": "Nombre",
        "PercentageTournamentCompletedLabel": "% de torneo completado",
        "ActivitiesCompletedLabel": "Actividades completadas",
        "NoRecordsinGridLabel": "No se encontraron registros.",
        "SearchPlaceholder": "Buscar por nombre de participante",
        "NoCompletedTournamentsMessage": "No hay ningún torneo completado en este momento. Vuelve a comprobarlo más tarde.",
        "ReportsDropdownInfoIconText": "El informe solo se puede generar para torneos completados.",
        "RefreshIconInfoText": "Haz clic en Actualizar para ver los datos más recientes",
        "ProvisioningErrorMessage": "Se ha producido un problema durante la configuración de la aplicación. Intente volver a configurar la aplicación.",
        "ProvisioningSuccessMessage": "El torneo de Teams se ha implementado correctamente. Actualice la aplicación para continuar.",
        "SpinnerMessage": "Configurando la aplicación.......",
        "ProvisioningSetupMessage": "Este proceso tardará unos minutos en completarse. No salga de la página hasta que vea el mensaje completado correctamente."
      }

});