define([], function () {
    return {
        "PropertyPaneDescription": "תיאור",
        "BasicGroupName": "שם קבוצה",
        "DescriptionFieldLabel": "שדה תיאור",
        "DigitalBadgePageTitle": "תג דיגיטלי",
        "LoadingSpinnerLabel": "טעינה...",
        "DigitalBadgeAppBannerAltText": "חברי צוות של Microsoft מנהלים בדיון",
        "PreAcceptPageTitle": "קבל את התג הדיגיטלי שלך!",
        "PreAcceptDisclaimer": "<span style='font-weight:bold;'>ברוך הבא לשירות התגים הדיגיטליים</span> <br/><br/> <span>כחלק מחברותך בתוכנית האלופים, זכית בתג דיגיטלי! שירות זה יאפשר לך '<em>לתבוע בעלות</em>' על התג הדיגיטלי על-ידי הוספה שלו לתמונת הפרופיל הקיימת שלך. <br/><br/> שים לב שפעולה זו תעדכן את תמונת הפרופיל שלך בכל Microsoft 365‏ (Exchange‏, Teams‏, SharePoint וכו').</span>",
        "PreAcceptDisclaimer2": "אם תרצה, <span style='font-weight:bold;'>תהיה לך אפשרות 'לשמור' העתק של תמונות הפרופיל הקיימת שלך</span>ללא התוספת של התג הדיגיטלי בשלבים הבאים. לחץ על 'קבל' כדי להמשיך (ייתכן שייפתח חלון מוקפץ ויבקש להירשם).",
        "NotQualifiedPreAcceptDisclaimer": "<span style='font-weight:bold;'>ברוך הבא לשירות התגים הדיגיטליים</span>. כחלק מחברותך בתוכנית האלופים, תוכל לזכות בתג דיגיטלי! שירות זה יאפשר לך '<em>לתבוע בעלות</em>' על התג הדיגיטלי על-ידי הוספה שלו לתמונת הפרופיל הקיימת שלך. שים לב שפעולה זו תעדכן את תמונת הפרופיל שלך בכל Microsoft 365‏ (Exchange‏, Teams‏, SharePoint וכו').",
        "HowtoGetDigitalBadgeText": "כיצד זוכים בתג אלוף",
        "MultipleBadgeMessage": "בחר תג מהרשימה שלהלן. התג שנבחר יוחל על תמונת הפרופיל שלך.",
        "NoBadgeMessage": "לא נמצאו תגים שתוכל לבחור. בדוק עם מנהל היישום.",
        "DigitalBadgeSubPageTitle": "כך התג הדיגיטלי שלך ייראה!",
        "ProfileImageAlt": "הפרופיל שלי תמונה הנמצאת בשימוש ברחבי O365, Teams וכן הלאה",
        "BadgeImageAlt": "פרס בצורת מדליה עם האות C במרכז מציין שאני חלק מתוכנית האלופים",
        "NoProfileImageAlt": "צללית של אדם המציינת היעדר של תמונת פרופיל מוחלת כעת בחשבונך",
        "ApplyButtonText": "החל תמונה",
        "ApplyButtonAriaDescription": "בלחיצה על לחצן זה אתה מעניק ל- Web Part של תוכנית האלופים הרשאה לעדכן את תמונת הפרופיל שלך בשמך.",
        "ApplyButton": "החל",
        "DownloadButtonText": "הורד",
        "DownloadButtonAriaDescription": "לחץ כדי להוריד את תמונת הפרופיל הנוכחית שלך",
        "DownloadingButtonText": "מוריד...",
        "DownloadedButtonText": "הורד",
        "DownloadedButtonSecondaryText": "ניתן למצוא את תמונת הפרופיל שהורדת בתיקיה 'הורדות' במכשיר שלך.",
        "DownloadButtonSecondaryText": "הורד את תמונת הפרופיל הנוכחית שלך",
        "PreApplyDisclaimer": "זוהי תצוגה מקדימה של תמונת הפרופיל שלך בתוספת התג הדיגיטלי. אם ברצונך להוריד את תמונת הפרופיל הקיימת לפני הוספת התג הדיגיטלי, לחץ על הקישור '<strong>הורד את תמונת הפרופיל הנוכחית שלך image</strong>'.<br />",
        "PreApplyDisclaimer1": "<br />לחיצה על 'החל תמונה' תעדכן את תמונת הפרופיל שלך ב- Microsoft 365 בתמונה חדשה זו. <strong>שים לב שפעולה זו תעדכן את תמונת הפרופיל שלך בכל Microsoft 365 ולא ניתן לבטל אותה דרך דף זה</strong>. <br/><br/>אם ברצונך לחזור לתמונה הישנה, תוכל להשתמש ב <a class='constAnchor' href='https://outlook.office365.com/owa/' target='_blank' aria-label='Open the Outlook web application in a new browser tab or window'>אפליקציית Outlook לאינטרנט</a>.",
        "NoProfileImageDescription": "אם לפרופיל שלך כבר משויכת תמונה, והודעה זו עדיין מוצגת, ייתכן שהתמונה שלך עדיין לא זמינה. נסה שוב מאוחר יותר, או פנה ל<a class='constAnchor' href='https://microsoft.service-now.com/' target='_blank' aria-description='Open the Outlook web application in a new browser tab or window'>צוות התמיכה</a> אם היא לא תופיע לאחר 24 שעות.",
        "AcceptButtonText": "קבל",
        "AcceptButtonAriaDescription": "בלחיצה על לחצן זה אתה מעניק ל- Web Part של תוכנית האלופים הרשאה לעדכן את תמונת הפרופיל שלך בשמך.",
        "UnauthorizedText": "אינך עומד בדרישות עבור תוכנית תג 'אלוף' בשלב זה",
        "ApplySpinnerLabel": "מחיל תמונת פרופיל חדשה בחשבון שלך...",
        "DigitalBadgeSuccessMessage": "<strong>ברכותינו!</strong> אספת בהצלחה את התג הדיגיטלי שלך ותמונת הפרופיל שלך עודכנה. יש להמתין עד 24 שעות עד להשתקפות של העדכון בכל יישומי Microsoft 365 (כולל Teams).",
        "DigitalMembersToolTip": "קבל את התג הדיגיטלי שלך והחל אותו על תמונת הפרופיל שלך",
        "DigitalBadgeLabel": "תג דיגיטלי",
        "AdminToolsLabel": "כלי מנהל מערכת",
        "AppHeaderTitleLabel": "טורניר של Teams",
        "AppLogoToolTip": "בית",
        "MoreInfoToolTip": "מידע נוסף",
        "SupportToolTip": "תמיכה",
        "FeedbackToolTip": "משוב",
        "WelcomeLabel": "ברוך הבא",
        "AboutHeaderLabel": "טורניר של Teams",
        "AboutContentLabel": "הטורניר של Teams מאפשר לארגון כולו את חוויות ההגדלה והלמידה של הבאת הטורנירים עם ערכת נושא של אימוץ לצורך נהיגה שימוש תקין. בפלטפורמה תוכל ליצור ולספק טורנירים כדי לעודד שימוש תקין בתרחישים, לעורר השראה למשתמשים על-ידי הפעלת קמפיינים המנחים למידתם חדשות, ולעקוב אחר פעולות הטורניר ולתעד הבאות כדי לקבל זיהוי והשפעה על אירועים מאוחרים.",
        "AdditionalResourcesHeaderLabel": "משאבים נוספים:",
        "AdditionalResourcesContentLabel": "קבוצת התמיכה ללקוחות Microsoft Teams מתמקדת באספקת פתרונות כגון אלה כדי לעורר השראה וכדי לסייע לך בהשגת מטרותיך. עקוב אחר משאבים אחרים אלה והצטרף אליהם כדי לקבל מידע נוסף מאיתנו ומקהילה:",
        "M365ChampionCommunityLinkLabel": "קהילת האלופים של Microsoft 365",
        "DrivingAdoptionLinkLabel": "קידום של אימוץ בקהילת Microsoft Technical Community",
        "CurrentVersionLabel": "הגירסה הנוכחית:",
        "LatestVersionLabel": "הגירסה העדכנית ביותר:",
        "TOTGitHubLinkLabel": "GitHub",
        "VisitLabel": "בקר בטורניר של דפי Teams לקבלת מידע נוסף:",
        "OverviewLabel": "מידע ומבט כולל על",
        "MSAdoptionHubLinkLabel": "מרכז האימוץ של Microsoft",
        "DocumentationLabel": "תיעוד טכני של פתרון וסקירה ארכיטקטונית של",
        "SaveButton": "שמור",
        "BackButton": "הקודם",
        "EnableTOTToolTip": "הפוך טורניר של Teams לזמין",
        "EnableTOTLabel": "הפוך טורניר של Teams לזמין",
        "CreateTournamentPageTitle": "צור טורניר",
        "CreateTournamentSuccessLabel": "הטורניר נוצר בהצלחה.",
        "TournamentNameLabel": "שם הטורניר",
        "TournamentNamePlaceHolderLabel": "שם הטורניר (255 תווים לכל היותר)",
        "TournamentNameErrorLabel": "נדרש שם של הטורניר.",
        "TournamentDescriptionLabel": "תיאור הטורניר",
        "TournamentDescPlaceHolderLabel": "תיאור של הטורניר (500 תווים לכל היותר)",
        "SelectTeamsActionsLabel": "בחר פעולות Teams:",
        "TeamsActionInfoToolTip": "בחר מבין פעולות Teams הזמינות להלן כדי לכלול בטורניר החדש. כדי להוסיף פעולות טורניר חדשות למבחר, בקר במקטע 'נהל פעולות טורניר' ב'כלי מנהל מערכת'.",
        "ActionErrorLabel": "בחר פעולה אחת לפחות ליצירת טורניר.",
        "CreateTournamentButton": "צור טורניר",
        "DuplicateTournamentNameError": "שם הטורניר כבר קיים. הזן שם אחר עבור הטורניר.",
        "CreateTournamentsButton": "צור טורנירים",
        "SingleTournamentLabel": "טורניר יחיד",
        "MultipleTournamentLabel": "טורנירים מרובים",
        "MultiTournamentStep": "שלב",
        "MultiTournamentStep1LinkLabel": "הורד תבנית",
        "MultiTournamentStep1Text": " מתבנית של קובץ לדוגמה",
        "MultiTournamentStep2": "הוסף פרטי טורניר לקובץ על-ידי ביצוע ההנחיות",
        "MultiTournamentStep3": "העלה את הקובץ",
        "UploadFileButton": "העלה קובץ",
        "RemoveFileLabel": "הסר קובץ",
        "ImportSpinnerMessage": "יוצר טורנירים.....",
        "ErrorMsgTournamentList": "אירעה שגיאה בעת יצירת פריט ברשימת הטורנירים. תקן את הנתונים ונסה שוב.",
        "ErrorMsgActionsList": "אירעה שגיאה בעת יצירת פריט ברשימת הפעולות. תקן את הנתונים ונסה שוב.",
        "ErrorMsgTournamentActionsList": "אירעה שגיאה בעת יצירת פריט ברשימת פעולות הטורניר. תקן את הנתונים ונסה שוב.",
        "LogMsgTournamentExists": "המערכת דילגה, מאחר שהטורניר",
        "LogMsgTournamentExists1": "כבר קיים.",
        "LogMsgDone": "טורניר",
        "LogMsgDone1": "נוצר.",
        "LogMsgInvalidTournamentName": "המערכת דילגה על כך, מאחר שאין לו שם טורניר חוקי.",
        "LogMsgInvalidTemplate": "המערכת דילגה על כך, מאחר שזו אינה תבנית חוקית.",
        "LogMsgMultipleTournaments": "המערכת דילגה על כך, מאחר שהיא כוללת יותר לשם טורניר אחד.",
        "LogMsgBlankSheet": "המערכת דילגה על פריט זה מכיוון שהוא ריק.",
        "LogProgress": " להלן ההתקדמות:",
        "ImportRule1": "אל תשנה את כותרות העמודות בתבנית",
        "ImportRule2": "אל תמחק את העמודות בתבנית",
        "ImportRule3": "הזן נתונים בכל העמודות הדרושות(*) המוזכרות בתבנית",
        "ImportRule4": "עקוב אחר מגבלת התווים והקלד המוזכר בתבנית עבור כל עמודה",
        "ImportRule5": "הזן נתונים עבור טורניר אחד בלבד בכל גיליון, כמו בנתונים לדוגמה",
        "ImportRule6": "ניתן ליצור 10 טורנירים בלבד בכל פעם",
        "ImportRule7": "ודא ששם הטורניר ייחודי",
        "TOTBreadcrumbLabel": "טורניר של Teams",
        "EnableTOTSuccessMessage": "הטורניר של Teams הופעל בהצלחה. רענן את האפליקציה לפני השימוש.",
        "TOTLeaderBoardPageTitle": "טבלת המובילים",
        "TOTMyDashboardPageTitle": "לוח המחוונים שלי",
        "ManageTournamentActionsToolTip": "גישה לרשימת פעולות הטורניר",
        "ManageTournamentActionsLabel": "ניהול פעולות טורניר",
        "ManageTournamentsLabel": "נהל טורנירים",
        "ManageAdminsToolTip": "גישה לרשימת מנהל מערכת",
        "ManageAdminsLabel": "נהל מנהלי מערכת",
        "ManageDigitalBadgesLabel": "נהל תגים דיגיטליים",
        "QuickLinksLabel": "קישורים מהירים",
        "ManageTournamentsPageTitle": "נהל טורנירים",
        "ManageToTLabel1": "ניתן להתחיל מספר טורנירים בכל פעם. עיין להלן לקבלת מידע על הטורנירים הפעילים הנוכחיים, היכולת להשלים את הטורניר, וכן על היכולת להתחיל טורניר חדש.",
        "ManageToTLabel2": "לאחר התחלה והשלמה של טורניר, לא יהיה ניתן להתחיל אותו מחדש. עם זאת, תוכל ליצור טורניר חדש באותה דרך אם ברצונך להשלים טורניר דומה!",
        "EndTournamentDialogMessage": "האם אתה בטוח שברצונך להשלים את הטורניר?",
        "StartTournamentDialogMessage": "האם אתה בטוח שברצונך להתחיל את הטורנירים החדשים?",
        "ConfirmLabel": "אשר",
        "YesButton": "כן",
        "NoButton": "לא",
        "SearchActiveTournaments": "חפש טורנירים פעילים",
        "SearchPendingTournaments": "חפש טורנירים כדי להתחיל",
        "SelectAllLabel": "בחר הכל",
        "NoSearchResults": "אין תוצאות התואמות לחיפוש שלך.",
        "ActiveTournamentLabel": "טורנירים פעילים",
        "EndTournamentButton": "השלם טורניר",
        "StartTournamentHeaderLabel": "התחל טורניר",
        "NoTournamentMessage": "לא נמצאו טורנירים. בדוק שוב מאוחר יותר.",
        "SelectTournamentMessage": "בחר טורניר אחד לפחות כדי להתחיל.",
        "SelectEndTournamentMessage": "בחר טורניר לסיום.",
        "StartTournamentButton": "התחל טורנירים",
        "EndTournamentSuccessMessage": "הטורניר הושלם בהצלחה.",
        "EnableTournamentSuccessMessage": "הטורנירים התחילו בהצלחה.",
        "CompleteTournamentSpinnerMessage": "משלים טורניר...",
        "EnableTournamentSpinnerMessage": "מפעיל טורנירים...",
        "NoActiveParticipantsMessage": "אין משתתפים פעילים כרגע. היה הראשון להשתתף ולרשום פעילות ב'לוח המחוונים שלי'!",
        "NoActiveTournamentMessage": "אין טורנירים פעילים כרגע. בדוק שוב מאוחר יותר.",
        "TournamentLabel": "טורניר",
        "DescriptionLabel": "תיאור",
        "NoActiveParticipantsErrorMessage": "אין משתתפים פעילים כרגע. היה הראשון להשתתף ולרשום פעילות מאת ",
        "PendingActionsLabel": "פעולות בהמתנה",
        "PendingActionsSuccessMessage": "אין עוד פעולות ממתינות בטורניר זה.",
        "SelectActionsErrorMessage": "בחר פעולה אחת לפחות כדי להמשיך.",
        "FormSavingMessage": "שומר את הפרטים שלך....",
        "CompletedActionsLabel": "פעולות שהושלמו",
        "RankLabel": "דרגה",
        "UserLabel": "משתמש",
        "MyDashboardInfoIconMessage": "קבל פרטים נוספים אודות פעולה זו",
        "SelectTournamentPlaceHolder": "בחר טורניר",
        "MyTournamentsLabel": "הטורנירים שלי",
        "OrLabel": "או",
        "MyTournamentsTooltip": "טורנירים פעילים שכבר השתתפת בהם",
        "PointsLabel": "נקודות",
        "TournamentRankLabel": "דירוג הטורניר",
        "ParticipantsLabel": "משתתפים",
        "TournamentReportsPageTitle": "דוח טורנירים",
        "TotalActivitiesLabel": "סך כל הפעילויות",
        "TotalPointsLabel": "סה\"כ נקודות",
        "TotalParticipantsLabel": "כל המשתתפים",
        "TotalPercentageCompletionLabel": "% מההשלמה הכוללת",
        "Top5ParticipantswithPointsLabel": "חמשת המשתתפים המובילים עם נקודות",
        "Top5TournamentswithParticipantsLabel": "חמשת הטורנירים המובילים עם משתתפים",
        "ParticipantsStatusLabel": "מצב המשתתפים",
        "ParticipantsDetailsLabel": "פרטי המשתתפים",
        "NameLabel": "שם",
        "PercentageTournamentCompletedLabel": "% מהטורניר הושלמו",
        "ActivitiesCompletedLabel": "פעילויות שהושלמו",
        "NoRecordsinGridLabel": "לא נמצאו רשומות.",
        "SearchPlaceholder": "חפש לפי כינוי של משתתף",
        "NoCompletedTournamentsMessage": "אין טורניר שהושלם כרגע. בדוק שוב מאוחר יותר.",
        "ReportsDropdownInfoIconText": "ניתן ליצור דוח רק עבור טורנירים שהושלמו.",
        "RefreshIconInfoText": "לחץ על 'רענן' כדי לראות את הנתונים העדכניים ביותר",
        "ProvisioningErrorMessage": "אירעה בעיה במהלך הגדרת היישום. נסה שוב להגדיר את האפליקציה.",
        "ProvisioningSuccessMessage": "הטורניר של Teams נפרס בהצלחה. רענן את האפליקציה כדי להמשיך.",
        "SpinnerMessage": "מגדיר את האפליקציה.....",
        "ProvisioningSetupMessage": "תהליך זה יימשך מספר רגעים. אל תנווט החוצה עד שתראה את ההודעה שהושלמה בהצלחה."
      }

});