define([], function () {
    return {
        "PropertyPaneDescription": "Descrição",
        "BasicGroupName": "Nome do grupo",
        "DescriptionFieldLabel": "Campo de Descrição",
        "DigitalBadgePageTitle": "Selo Digital",
        "LoadingSpinnerLabel": "Carregando...",
        "DigitalBadgeAppBannerAltText": "Membros da equipe da Microsoft participando de uma discussão",
        "PreAcceptPageTitle": "Solicite seu selo digital!",
        "PreAcceptDisclaimer": "<span style='font-weight:bold;'>Bem-vindo ao utilitário do selo digital</span> <br/><br/> <span>Como parte de sua associação ao Programa Campeões, você ganhou um selo digital! Esse utilitário permitirá que você '<em>obtenha</em>' seu selo digital sobrepondo-o em cima de sua foto de perfil existente. <br/><br/> Observe que isso atualizará sua foto de perfil em todo o Microsoft 365 (Exchange, Teams, SharePoint, etc.).</span>",
        "PreAcceptDisclaimer2": "Se desejar, <span style='font-weight:bold;'>você terá a oportunidade de 'salvar' uma cópia da sua foto de perfil existente</span> sem a sobreposição do selo digital nas etapas seguintes. Clique em 'Aceitar' para continuar (você pode ver um pop-up aberto e solicitar a entrada).",
        "NotQualifiedPreAcceptDisclaimer": "<span style='font-weight:bold;'>Bem-vindo ao utilitário do selo digital</span>. Como parte de sua associação ao Programa Campeões, você pode ganhar um selo digital! Esse utilitário permitirá que você '<em>obtenha</em>' seu selo digital sobrepondo-o em cima de sua foto de perfil existente. Observe que isso atualizará sua foto de perfil em todo o Microsoft 365 (Exchange, Teams, SharePoint, etc.)",
        "HowtoGetDigitalBadgeText": "Como obter uma Selo de Campeão",
        "MultipleBadgeMessage": "Selecione um selo na lista abaixo. O selo selecionado será aplicado na imagem do seu perfil.",
        "NoBadgeMessage": "Nenhum selo encontrado para você selecionar. Verifique com o Administrador de Aplicativos.",
        "DigitalBadgeSubPageTitle": "Veja como seu selo digital ficará!",
        "ProfileImageAlt": "Minha imagem de perfil usada no O365, no Teams, etc.",
        "BadgeImageAlt": "Prêmio em forma de medalha com a letra C no meio que indica que eu sou parte do Programa Dos Campeão",
        "NoProfileImageAlt": "Silhueta de uma pessoa, indicando que nenhuma imagem de perfil está atualmente aplicada à sua conta",
        "ApplyButtonText": "Aplicar imagem",
        "ApplyButtonAriaDescription": "Ao clicar neste botão, você dará permissão à Web Part do Programa Campeões para atualizar sua foto de perfil em seu nome.",
        "ApplyButton": "Aplicar",
        "DownloadButtonText": "Baixar",
        "DownloadButtonAriaDescription": "Clique para baixar sua imagem de perfil atual",
        "DownloadingButtonText": "Baixando...",
        "DownloadedButtonText": "Baixado",
        "DownloadedButtonSecondaryText": "A imagem de perfil baixada pode ser encontrada na pasta Downloads do dispositivo.",
        "DownloadButtonSecondaryText": "Baixar sua imagem de perfil atual",
        "PreApplyDisclaimer": "Esta é uma visualização da sua nova foto de perfil, incluindo o selo digital. Se desejar baixar sua foto de perfil existente antes de aplicar o selo digital, clique no link '<strong>Baixar sua imagem de perfil atual</strong>'.<br />",
        "PreApplyDisclaimer1": "<br />Clicar em \"Aplicar imagem\" atualizará sua imagem de perfil do Microsoft 365 com esta nova imagem. <strong>Observe que isso atualizará sua foto de perfil em todo o Microsoft 365 e não poderá ser revertido por meio desta página</strong>. <br/><br/>Se desejar alterar sua imagem de volta, você poderá usar o <a class='constAnchor' href='https://outlook.office365.com/owa/' target='_blank' aria-label='Open the Outlook web application in a new browser tab or window'>aplicativo da Web do Outlook</a>.",
        "NoProfileImageDescription": "Se você já associou uma foto ao seu perfil e ainda estiver vendo esta mensagem, sua foto pode ainda não estar disponível. Tente novamente mais tarde ou contate a <a class='constAnchor' href='https://microsoft.service-now.com/' target='_blank' aria-description='Open the Outlook web application in a new browser tab or window'>assistência técnica</a> se ela ainda não apareceu após 24 horas.",
        "AcceptButtonText": "Aceitar",
        "AcceptButtonAriaDescription": "Ao clicar neste botão, você dará permissão à Web Part do Programa Campeões para atualizar sua foto de perfil em seu nome.",
        "UnauthorizedText": "Você não está qualificado para o Programa de Selo de Campeão no momento",
        "ApplySpinnerLabel": "Aplicando nova imagem de perfil à sua conta...",
        "DigitalBadgeSuccessMessage": "<strong>Parabéns!</strong> Você reivindicou com êxito seu selo digital e sua foto de perfil foi atualizada. Aguarde até 24 horas para ver a atualização refletida em todos os aplicativos do Microsoft 365 (incluindo o Teams).",
        "DigitalMembersToolTip": "Obtenha seu selo digital e aplique-o à sua imagem de perfil",
        "DigitalBadgeLabel": "Selo Digital",
        "AdminToolsLabel": "Ferramentas do Administrador",
        "AppHeaderTitleLabel": "Campeonato do Teams",
        "AppLogoToolTip": "Home",
        "MoreInfoToolTip": "Mais Informações",
        "SupportToolTip": "Suporte",
        "FeedbackToolTip": "Comentários",
        "WelcomeLabel": "Bem-vindo(a)",
        "AboutHeaderLabel": "Campeonato do Teams",
        "AboutContentLabel": "O Campeonato do Teams permite a toda a organização a gamificação e as experiências de aprendizado de trazer campeonatos com tema de adoção para promover o uso íntegro. Dentro da plataforma, você pode criar e fornecer campeonatos para ajudar a conduzir o uso íntegro de cenários, inspirar os usuários executando campanhas solicitando novos aprendizados e acompanhar e registrar ações de campeonato para pós-reconhecimento e impacto de eventos.",
        "AdditionalResourcesHeaderLabel": "Recursos Adicionais:",
        "AdditionalResourcesContentLabel": "O Grupo de Atendimento ao Cliente do Microsoft Teams está focado em fornecer soluções como estas para inspirar e ajudar você a alcançar suas metas. Siga e ingresse por meio desses outros recursos para saber mais sobre nós e a comunidade:",
        "M365ChampionCommunityLinkLabel": "Comunidade de Campeões do Microsoft 365",
        "DrivingAdoptionLinkLabel": "Impulsionando a adoção na Microsoft Technical Community",
        "CurrentVersionLabel": "Versão atual:",
        "LatestVersionLabel": "Versão Mais Recente:",
        "TOTGitHubLinkLabel": "GitHub",
        "VisitLabel": "Visite as páginas do Campeonato do Teams para saber mais:",
        "OverviewLabel": "Visão geral e Informações sobre nosso",
        "MSAdoptionHubLinkLabel": "Hub de Adoção da Microsoft",
        "DocumentationLabel": "Documentação técnica da solução e visão geral da arquitetura sobre",
        "SaveButton": "Salvar",
        "BackButton": "Voltar",
        "EnableTOTToolTip": "Habilitar o Campeonato do Teams",
        "EnableTOTLabel": "Habilitar o Campeonato do Teams",
        "CreateTournamentPageTitle": "Criar Campeonato",
        "CreateTournamentSuccessLabel": "Campeonato criado com êxito.",
        "TournamentNameLabel": "Nome do Campeonato",
        "TournamentNamePlaceHolderLabel": "Nome do Campeonato (Máximo de 255 caracteres)",
        "TournamentNameErrorLabel": "O Nome do Campeonato é obrigatório.",
        "TournamentDescriptionLabel": "Descrição do Campeonato",
        "TournamentDescPlaceHolderLabel": "Descrição do torneio (Máximo 500 caracteres)",
        "SelectTeamsActionsLabel": "Selecionar as Ações do Teams:",
        "TeamsActionInfoToolTip": "Selecione uma das ações do Teams disponíveis abaixo para incluir no novo campeonato. Para adicionar novas ações do campeonato para escolher, visite Gerenciar Ações de Campeonato nas Ferramentas de Administração.",
        "ActionErrorLabel": "Selecione pelo menos uma ação para criar um campeonato.",
        "CreateTournamentButton": "Criar Campeonato",
        "DuplicateTournamentNameError": "O nome do campeonato já existe. Insira outro nome para o campeonato.",
        "CreateTournamentsButton": "Crie Campeonatos",
        "SingleTournamentLabel": "Campeonato Único",
        "MultipleTournamentLabel": "Vários Campeonatos",
        "MultiTournamentStep": "Etapa",
        "MultiTournamentStep1LinkLabel": "Baixar Modelo",
        "MultiTournamentStep1Text": " de formato de arquivo de amostra",
        "MultiTournamentStep2": "Adicione detalhes do campeonato ao arquivo seguindo as diretrizes",
        "MultiTournamentStep3": "Fazer upload do arquivo",
        "UploadFileButton": "Carregar Arquivo",
        "RemoveFileLabel": "Remover Arquivo",
        "ImportSpinnerMessage": "Criando campeonatos.......",
        "ErrorMsgTournamentList": "Erro ao criar um item na lista Campeonatos. Corrija os dados e tente novamente.",
        "ErrorMsgActionsList": "Erro ao criar um item na lista Ações. Corrija os dados e tente novamente.",
        "ErrorMsgTournamentActionsList": "Ocorreu um erro ao criar um item na lista Ações de Campeonato. Corrija os dados e tente novamente.",
        "LogMsgTournamentExists": "Ignorado, pois o campeonato",
        "LogMsgTournamentExists1": "já existe.",
        "LogMsgDone": "Campeonato",
        "LogMsgDone1": "criado.",
        "LogMsgInvalidTournamentName": "Ignorado, pois ele não tem um Nome de Campeonato válido.",
        "LogMsgInvalidTemplate": "Ignorado, pois não é um modelo válido.",
        "LogMsgMultipleTournaments": "Ignorado, pois ele tem mais de um Nome de Campeonato.",
        "LogMsgBlankSheet": "Ignorado, pois está em branco.",
        "LogProgress": " Abaixo está o progresso:",
        "ImportRule1": "Não modificar os cabeçalhos de coluna no modelo",
        "ImportRule2": "Não excluir as colunas no modelo",
        "ImportRule3": "Insira os dados em todas as colunas obrigatórias (*) mencionadas no modelo",
        "ImportRule4": "Siga o limite de caracteres e o tipo mencionado no modelo para cada coluna",
        "ImportRule5": "Insira dados para apenas 1 campeonato em cada planilha de acordo com os dados de exemplo fornecidos",
        "ImportRule6": "Somente 10 campeonatos podem ser criados por vez",
        "ImportRule7": "Certifique-se de que o Nome do Campeonato é único",
        "TOTBreadcrumbLabel": "Campeonato do Teams",
        "EnableTOTSuccessMessage": "Campeonato do Teams habilitado com êxito. Atualize o aplicativo antes de usar.",
        "TOTLeaderBoardPageTitle": "Quadro de Líderes",
        "TOTMyDashboardPageTitle": "Meu Painel",
        "ManageTournamentActionsToolTip": "Acessando a Lista de Ações do Campeonato",
        "ManageTournamentActionsLabel": "Gerenciar as Ações do Campeonato",
        "ManageTournamentsLabel": "Gerenciar Campeonatos",
        "ManageAdminsToolTip": "Acessando a Lista de Administradores",
        "ManageAdminsLabel": "Gerenciar Administradores",
        "ManageDigitalBadgesLabel": "Gerenciar os Selos Digitais",
        "QuickLinksLabel": "Links Rápidos",
        "ManageTournamentsPageTitle": "Gerenciar Campeonatos",
        "ManageToTLabel1": "Vários campeonatos podem ser iniciados por vez. Veja abaixo os campeonatos atuais ativos, a capacidade de concluir o campeonato, bem como a capacidade de iniciar um novo campeonato.",
        "ManageToTLabel2": "Depois que um campeonato for iniciado e concluído, ele não estará disponível para iniciar novamente; no entanto, você pode criar um novo campeonato usando as mesmas ações se quiser concluir um campeonato semelhante!",
        "EndTournamentDialogMessage": "Tem certeza de que deseja concluir o campeonato?",
        "StartTournamentDialogMessage": "Tem certeza de que deseja iniciar o novo campeonato?",
        "ConfirmLabel": "Confirmar",
        "YesButton": "Sim",
        "NoButton": "Não",
        "SearchActiveTournaments": "Pesquisar campeonatos ativos",
        "SearchPendingTournaments": "Pesquisar campeonatos para começar",
        "SelectAllLabel": "Selecionar Tudo",
        "NoSearchResults": "Não há resultados correspondentes à sua pesquisa.",
        "ActiveTournamentLabel": "Campeonatos Ativos",
        "EndTournamentButton": "Campeonato Concluído",
        "StartTournamentHeaderLabel": "Iniciar Campeonato",
        "NoTournamentMessage": "Nenhum campeonato encontrado. Verifique novamente mais tarde.",
        "SelectTournamentMessage": "Selecione pelo menos um campeonato para começar.",
        "SelectEndTournamentMessage": "Selecione um campeonato para concluir.",
        "StartTournamentButton": "Iniciar Campeonato(s)",
        "EndTournamentSuccessMessage": "Campeonato concluído com êxito.",
        "EnableTournamentSuccessMessage": "Torneio(s) iniciado(s) com êxito.",
        "CompleteTournamentSpinnerMessage": "Completando o Campeonato...",
        "EnableTournamentSpinnerMessage": "Habilitando o(s) Campeonato(s)...",
        "NoActiveParticipantsMessage": "Não há participantes ativos no momento. Seja o primeiro a participar e registrar uma atividade em Meu Painel!",
        "NoActiveTournamentMessage": "Não há nenhum campeonato ativo no momento. Verifique novamente mais tarde.",
        "TournamentLabel": "Campeonato",
        "DescriptionLabel": "Descrição",
        "NoActiveParticipantsErrorMessage": "Não há participantes ativos no momento. Seja o primeiro a participar e registrar uma atividade de ",
        "PendingActionsLabel": "Ações Pendentes",
        "PendingActionsSuccessMessage": "Não há mais ações pendentes neste campeonato.",
        "SelectActionsErrorMessage": "Selecione pelo menos uma ação para continuar.",
        "FormSavingMessage": "Salvando seus detalhes....",
        "CompletedActionsLabel": "Ações Concluídas",
        "RankLabel": "Classificar",
        "UserLabel": "Usuário",
        "MyDashboardInfoIconMessage": "Saiba mais sobre essa ação",
        "SelectTournamentPlaceHolder": "Selecionar Campeonato",
        "MyTournamentsLabel": "Meus Campeonatos",
        "OrLabel": "OU",
        "MyTournamentsTooltip": "Campeonatos ativos dos quais você já participou",
        "PointsLabel": "Pontos",
        "TournamentRankLabel": "Classificação do Campeonato",
        "ParticipantsLabel": "Participantes",
        "TournamentReportsPageTitle": "Relatório dos Campeonatos",
        "TotalActivitiesLabel": "Total de Atividades",
        "TotalPointsLabel": "Total de Pontos",
        "TotalParticipantsLabel": "Total de Participantes",
        "TotalPercentageCompletionLabel": "% do Total da Conclusão",
        "Top5ParticipantswithPointsLabel": "Os 5 Principais Participantes com Pontos",
        "Top5TournamentswithParticipantsLabel": "Os 5 Principais Campeonatos com Participantes",
        "ParticipantsStatusLabel": "Status dos participantes",
        "ParticipantsDetailsLabel": "Detalhes dos Participantes",
        "NameLabel": "Nome",
        "PercentageTournamentCompletedLabel": "% do Campeonato Concluído",
        "ActivitiesCompletedLabel": "Atividades Concluídas",
        "NoRecordsinGridLabel": "Nenhum Registro Encontrado!",
        "SearchPlaceholder": "Pesquisar por Nome do Participante",
        "NoCompletedTournamentsMessage": "Não há nenhum campeonato concluído no momento. Verifique novamente mais tarde.",
        "ReportsDropdownInfoIconText": "O relatório só pode ser gerado para campeonatos concluídos.",
        "RefreshIconInfoText": "Clique em atualizar para ver os dados mais recentes",
        "ProvisioningErrorMessage": "Ocorreu um problema durante a configuração do aplicativo. Tente configurar o aplicativo novamente.",
        "ProvisioningSuccessMessage": "O campeonato do Teams foi implantado com êxito. Atualize o aplicativo para continuar.",
        "SpinnerMessage": "Configurando o App.....",
        "ProvisioningSetupMessage": "Este processo levará alguns minutos para ser concluído. Não saia até ver a mensagem concluída com êxito."
      }

});