define([], function () {
    return {
        "PropertyPaneDescription": "Описание",
        "BasicGroupName": "Имя группы",
        "DescriptionFieldLabel": "Поле описания",
        "DigitalBadgePageTitle": "Цифровой значок",
        "LoadingSpinnerLabel": "Загрузка...",
        "DigitalBadgeAppBannerAltText": "Участники команды Майкрософт участвуют в обсуждении",
        "PreAcceptPageTitle": "Получите цифровой значок!",
        "PreAcceptDisclaimer": "<span style='font-weight:bold;'>Вас приветствует служебная программа цифровых значков</span> <br/><br/> <span>Вы заработали цифровой значок, участвуя в Программе чемпионов! Эта служебная программа поможет вам \"<em>получить</em>\" цифровой значок, наложив его поверх вашего аватара. <br/><br/> Обратите внимание, что ваш аватар изменится во всех продуктах Microsoft 365 (Exchange, Teams, SharePoint и т. д.).</span>",
        "PreAcceptDisclaimer2": "При желании <span style='font-weight:bold;'>у вас будет возможность \"сохранить\" копию существующего изображения профиля</span> без наложения цифрового значка на последующих шагах. Нажмите «Принять», чтобы продолжить (вы можете увидеть всплывающее окно с запросом на вход).",
        "NotQualifiedPreAcceptDisclaimer": "<span style='font-weight:bold;'>Вас приветствует служебная программа цифровых значков</span>. Участвуя в Программе чемпионов, вы можете зарабатывать цифровые значки! Эта служебная программа поможет вам \"<em>получить</em>\" цифровой значок, наложив его поверх вашего аватара. Обратите внимание, что ваш аватар изменится во всех продуктах Microsoft 365 (Exchange, Teams, SharePoint и т. д.).",
        "HowtoGetDigitalBadgeText": "Как получить эмблему Champion",
        "MultipleBadgeMessage": "Выберите значок из списка ниже. Выбранный значок будет применен к вашему аватару.",
        "NoBadgeMessage": "Не найдены значки для выбора. Обратитесь к администратору приложения.",
        "DigitalBadgeSubPageTitle": "Вот как будет выглядеть ваша цифровая эмблема!",
        "ProfileImageAlt": "Мой профиль, используемый в Office 365, Teams и т. д.",
        "BadgeImageAlt": "Награда в виде медали с буквой С посередине, означающей, что я участвую в программе Champions",
        "NoProfileImageAlt": "Силуэт человека, означающий, что изображение профиля в настоящее время не применяется к вашей учетной записи.",
        "ApplyButtonText": "Применить изображение",
        "ApplyButtonAriaDescription": "Нажимая эту кнопку, вы даете веб-части программы Champions разрешение на обновление изображения вашего профиля от вашего имени.",
        "ApplyButton": "Применить",
        "DownloadButtonText": "Скачать",
        "DownloadButtonAriaDescription": "Щелкните, чтобы скачать текущее изображение профиля",
        "DownloadingButtonText": "Скачивание…",
        "DownloadedButtonText": "Скачано",
        "DownloadedButtonSecondaryText": "Скачанные изображения профиля можно найти в папке \"Загрузки\" вашего устройства.",
        "DownloadButtonSecondaryText": "Скачать текущее изображение профиля",
        "PreApplyDisclaimer": "Это предварительный просмотр вашего нового изображения профиля, включая цифровой значок. Если вы хотите загрузить существующее изображение профиля перед применением цифрового значка, нажмите ссылку «<strong>Загрузить текущее изображение профиля</strong>».<br />",
        "PreApplyDisclaimer1": "<br />Нажатие «Применить изображение» заменит изображение вашего профиля Microsoft 365 новым изображением. <strong>Обратите внимание, что при этом изображение вашего профиля будет обновлено во всех приложениях Microsoft 365, и его нельзя отменить на этой странице</strong>. <br/><br/>Если вы хотите вернуть свое изображение обратно, вы можете использовать <a class='constAnchor' href='https://outlook.office365.com/owa/' target='_blank ' aria-label='Откройте веб-приложение Outlook в новой вкладке или окне браузера'>Веб-приложение Outlook</a>.",
        "NoProfileImageDescription": "Если вы уже связали изображение со своим профилем и все еще видите это сообщение, возможно, ваше изображение еще недоступно. Повторите попытку позже или свяжитесь с <a class='constAnchor' href='https://microsoft.service-now.com/' target='_blank' aria-description='Open the Outlook web application in a new browser tab or window'>справочная служба</a>, если она по-прежнему не отображается через 24 часа.",
        "AcceptButtonText": "Принять",
        "AcceptButtonAriaDescription": "Нажимая эту кнопку, вы даете веб-части программы Champions разрешение на обновление изображения вашего профиля от вашего имени.",
        "UnauthorizedText": "В настоящее время вы не соответствуете требованиям для участия в программе Champion Badge.",
        "ApplySpinnerLabel": "Применение нового образа профиля к вашей учетной записи...",
        "DigitalBadgeSuccessMessage": "<strong>Поздравляем!</strong> Вы успешно запросили цифровой значок, и ваш аватар обновлен. Подождите до 24 часов, чтобы увидеть обновление, отраженное во всех Microsoft 365 приложениях (включая Teams).",
        "DigitalMembersToolTip": "Получите цифровой значок и примените его к изображению профиля",
        "DigitalBadgeLabel": "Цифровой значок",
        "AdminToolsLabel": "Средства администрирования",
        "AppHeaderTitleLabel": "Турнир Teams",
        "AppLogoToolTip": "Домашняя страница",
        "MoreInfoToolTip": "Дополнительные сведения",
        "SupportToolTip": "Поддержка",
        "FeedbackToolTip": "Обратная связь",
        "WelcomeLabel": "Добро пожаловать!",
        "AboutHeaderLabel": "Турнир Teams",
        "AboutContentLabel": "Турнир Teams позволяет всей организации использовать палитру и учебные возможности для внедрения турниров на темы внедрения для обеспечения работоспособного использования. На платформе вы можете создавать и доставлять турниры, чтобы помочь улучшить использование сценариев, помочь пользователям в работе, запуская кампании, запрашивая новые учебные материалы, а также отслеживать и записывать турнирные действия для распознавания и влияния событий после событий.",
        "AdditionalResourcesHeaderLabel": "Дополнительные ресурсы:",
        "AdditionalResourcesContentLabel": "Группа поддержки клиентов Microsoft Teams занимается предоставлением таких решений, которые вдохновляют и помогают вам в достижении ваших целей. Следите за новостями и присоединяйтесь к этим другим ресурсам, чтобы узнать больше от нас и сообщества:",
        "M365ChampionCommunityLinkLabel": "Сообщество Microsoft 365 Champion",
        "DrivingAdoptionLinkLabel": "Внедрение в Microsoft Technical Community",
        "CurrentVersionLabel": "Текущая версия:",
        "LatestVersionLabel": "Последняя версия:",
        "TOTGitHubLinkLabel": "GitHub",
        "VisitLabel": "Дополнительные сведения см. на страницах турнира Teams:",
        "OverviewLabel": "Обзор и информация о наших",
        "MSAdoptionHubLinkLabel": "Microsoft Adoption Hub",
        "DocumentationLabel": "Техническая документация решения и обзор архитектуры по",
        "SaveButton": "Сохранить",
        "BackButton": "Назад",
        "EnableTOTToolTip": "Включить турнир Teams",
        "EnableTOTLabel": "Включить турнир Teams",
        "CreateTournamentPageTitle": "Создать турнир",
        "CreateTournamentSuccessLabel": "Турнир успешно создан.",
        "TournamentNameLabel": "Название турнира",
        "TournamentNamePlaceHolderLabel": "Название турнира (максимум 255 символов)",
        "TournamentNameErrorLabel": "Необходимо указать название турнира.",
        "TournamentDescriptionLabel": "Описание турнира",
        "TournamentDescPlaceHolderLabel": "Описание турнира (не более 500 символов)",
        "SelectTeamsActionsLabel": "Выберите действия Teams:",
        "TeamsActionInfoToolTip": "Выберите из доступных ниже действий Teams, чтобы включить их в новый турнир. Чтобы добавить для выбора новые турнирные действия, перейдите в раздел \"Управление действиями турнира\" в Инструментах администратора.",
        "ActionErrorLabel": "Выберите хотя бы одно действие, чтобы создать турнир.",
        "CreateTournamentButton": "Создать турнир",
        "DuplicateTournamentNameError": "Имя турнира уже существует. Введите другое имя турнира.",
        "CreateTournamentsButton": "Создание турниров",
        "SingleTournamentLabel": "Одиночный турнир",
        "MultipleTournamentLabel": "Множественные турниры",
        "MultiTournamentStep": "Шаг",
        "MultiTournamentStep1LinkLabel": "Скачать шаблон",
        "MultiTournamentStep1Text": " примера формата файла",
        "MultiTournamentStep2": "Добавьте сведения о турнире в файл, выполнив следующие инструкции",
        "MultiTournamentStep3": "Выгрузить файл",
        "UploadFileButton": "Выгрузить файл",
        "RemoveFileLabel": "Удалить файл",
        "ImportSpinnerMessage": "Создание турниров...",
        "ErrorMsgTournamentList": "Произошла ошибка при создании элемента в списке турниров. Исправьте данные и повторите попытку.",
        "ErrorMsgActionsList": "Произошла ошибка при создании элемента в списке действий. Исправьте данные и повторите попытку.",
        "ErrorMsgTournamentActionsList": "Произошла ошибка при создании элемента в списке действий турнира. Исправьте данные и повторите попытку.",
        "LogMsgTournamentExists": "Пропущено, так как турнир",
      "LogMsgTournamentExists1": "уже существует.",
        "LogMsgDone": "Турнир",
        "LogMsgDone1": "Создано",
        "LogMsgInvalidTournamentName": "Пропущено, так как у него нет допустимого имени турнира.",
        "LogMsgInvalidTemplate": "Пропущено, так как он не является допустимым шаблоном.",
        "LogMsgMultipleTournaments": "Пропущено, так как оно содержит более одного имени турнира.",
        "LogMsgBlankSheet": "Пропущено, так как оно пустое.",
        "LogProgress": " Ниже приведен ход выполнения:",
        "ImportRule1": "Не изменять заголовки столбцов в шаблоне",
        "ImportRule2": "Не удалять столбцы в шаблоне",
        "ImportRule3": "Введите данные во всех обязательных (*) столбцах, упомянутых в шаблоне",
        "ImportRule4": "Соблюдайте лимит символов и введите указанные в шаблоне для каждого столбца.",
        "ImportRule5": "Введите данные только для 1 турнира на каждом листе согласно представленному образцу данных",
        "ImportRule6": "Одновременно можно создать только 10 турниров",
        "ImportRule7": "Убедитесь, что название турнира уникально",
        "TOTBreadcrumbLabel": "Турнир Teams",
        "EnableTOTSuccessMessage": "Турнир Teams включен. Обновите приложение перед использованием.",
        "TOTLeaderBoardPageTitle": "Доска лидеров",
        "TOTMyDashboardPageTitle": "Моя панель мониторинга",
        "ManageTournamentActionsToolTip": "Доступ к списку действий турнира",
        "ManageTournamentActionsLabel": "Управление действиями турнира",
        "ManageTournamentsLabel": "Управление турнирами",
        "ManageAdminsToolTip": "Доступ к списку администраторов",
        "ManageAdminsLabel": "Управление администраторами",
        "ManageDigitalBadgesLabel": "Управление цифровыми значками",
        "QuickLinksLabel": "Быстрые ссылки",
        "ManageTournamentsPageTitle": "Управление турнирами",
        "ManageToTLabel1": "Одновременно можно начать несколько турниров. Ниже отображаются активные турниры, возможность завершить турнир, а также возможность начать новый турнир.",
        "ManageToTLabel2": "После начала и завершения турнира он будет недоступен для повторного запуска; однако если вы хотите завершить похожий турнир, то можете создать новый, выполнив те же действия.",
        "EndTournamentDialogMessage": "Вы действительно хотите завершить турнир?",
        "StartTournamentDialogMessage": "Вы действительно хотите начать новый турнир?",
        "ConfirmLabel": "Подтвердить",
        "YesButton": "Да",
        "NoButton": "Нет",
        "SearchActiveTournaments": "Поиск активных турниров",
        "SearchPendingTournaments": "Поиск турниров для начала",
        "SelectAllLabel": "Выбрать все",
        "NoSearchResults": "Нет результатов, соответствующих вашему запросу.",
        "ActiveTournamentLabel": "Активные турниры",
        "EndTournamentButton": "Завершить турнир",
        "StartTournamentHeaderLabel": "Начать турнир",
        "NoTournamentMessage": "Турниры не найдены. Вернитесь сюда позже.",
        "SelectTournamentMessage": "Выберите хотя бы один турнир, чтобы начать.",
        "SelectEndTournamentMessage": "Выберите турнир для завершения.",
        "StartTournamentButton": "Запустить турниры",
        "EndTournamentSuccessMessage": "Турнир успешно завершен.",
        "EnableTournamentSuccessMessage": "Турниры успешно запущены.",
        "CompleteTournamentSpinnerMessage": "Завершение турнира...",
        "EnableTournamentSpinnerMessage": "Включение турниров...",
        "NoActiveParticipantsMessage": "На данный момент активных участников нет. Будьте первым, кто примет участие и зарегистрирует активность в Личном кабинете!",
        "NoActiveTournamentMessage": "В данный момент нет активных турниров. Вернитесь сюда позже.",
        "TournamentLabel": "Турнир",
        "DescriptionLabel": "Описание",
        "NoActiveParticipantsErrorMessage": "На данный момент активных участников нет. Будьте первым, кто примет участие и зарегистрирует активность от ",
        "PendingActionsLabel": "Ожидающие выполнения действия",
        "PendingActionsSuccessMessage": "В этом турнире больше нет ожидающих выполнения действий.",
        "SelectActionsErrorMessage": "Выберите хотя бы одно действие, чтобы продолжить.",
        "FormSavingMessage": "Сохранение сведений....",
        "CompletedActionsLabel": "Завершенные действия",
        "RankLabel": "Рейтинг",
        "UserLabel": "Пользователь",
        "MyDashboardInfoIconMessage": "Подробнее об этом действии",
        "SelectTournamentPlaceHolder": "Выбор турнира",
        "MyTournamentsLabel": "Мои турниры",
        "OrLabel": "ИЛИ",
        "MyTournamentsTooltip": "Активные турниры, в которых вы уже участвовали",
        "PointsLabel": "Баллы",
        "TournamentRankLabel": "Рейтинг турнира",
        "ParticipantsLabel": "Участники",
        "TournamentReportsPageTitle": "Отчет о турнирах",
        "TotalActivitiesLabel": "Всего действий",
        "TotalPointsLabel": "Сумма баллов",
        "TotalParticipantsLabel": "Всего участников",
        "TotalPercentageCompletionLabel": "% от общего завершения",
        "Top5ParticipantswithPointsLabel": "5 лучших участников с баллами",
        "Top5TournamentswithParticipantsLabel": "Пять лучших турниров с участниками",
        "ParticipantsStatusLabel": "Состояние участников",
        "ParticipantsDetailsLabel": "Сведения об участниках",
        "NameLabel": "Имя",
        "PercentageTournamentCompletedLabel": "% турнира завершено",
        "ActivitiesCompletedLabel": "Действия завершены",
        "NoRecordsinGridLabel": "Записи не найдены!",
        "SearchPlaceholder": "Поиск по имени участника",
        "NoCompletedTournamentsMessage": "В данный момент нет завершенных турниров. Вернитесь сюда позже.",
        "ReportsDropdownInfoIconText": "Отчет можно создать только для завершенных турниров.",
        "RefreshIconInfoText": "Нажмите кнопку \"Обновить\", чтобы просмотреть последние данные",
        "ProvisioningErrorMessage": "Во время настройки приложения возникла проблема. Попробуйте настроить приложение еще раз.",
        "ProvisioningSuccessMessage": "Турнир Teams успешно развернут. Обновите приложение, чтобы продолжить.",
        "SpinnerMessage": "Настройка приложения.....",
        "ProvisioningSetupMessage": "Этот процесс займет несколько минут. Пожалуйста, не уходите, пока не увидите сообщение об успешном завершении."
      }

});