define([], function () {
    return {
        "PropertyPaneDescription": "描述",
        "BasicGroupName": "群組名稱",
        "DescriptionFieldLabel": "描述欄位",
        "DigitalBadgePageTitle": "數位徽章",
        "LoadingSpinnerLabel": "正在載入...",
        "DigitalBadgeAppBannerAltText": "參與討論的 Microsoft 小組成員",
        "PreAcceptPageTitle": "領取您的數位徽章!",
        "PreAcceptDisclaimer": "<span style='font-weight:bold;'>歡迎使用數位徽章公用程式</span> <br/><br/> <span>作為您擁護者計畫的成員資格的一部分，您已獲得數位徽章! 此公用程式可讓您在現有的個人資料圖片上重迭數位徽章，以「<em></em>」您的數位徽章。 <br/><br/> 請注意，這將會更新您在所有 exchange、Teams、SharePoint 等所有Microsoft 365 (個人資料圖片)。</span>",
        "PreAcceptDisclaimer2": "如有需要，<span style='font-weight:bold;'>您將有機會「儲存」您現有的個人資料圖片複本</span>而不會在後續步驟中重迭數位徽章。請按一下 [接受] 以繼續 (您可能會看到快顯視窗開啟，並提示您) 登入。",
        "NotQualifiedPreAcceptDisclaimer": "<span style='font-weight:bold;'>歡迎使用數位徽章公用程式</span>。作為您擁護者計畫的成員資格的一部分，您可獲得數位徽章! 此公用程式可讓您在現有的個人資料圖片上重迭數位徽章，以「<em></em>」您的數位徽章。請注意，這將會更新您在所有 exchange、Teams、SharePoint 等所有Microsoft 365 (個人資料圖片)。",
        "HowtoGetDigitalBadgeText": "如何取得擁護者徽章",
        "MultipleBadgeMessage": "從下列清單選取徽章。選取的徽章將套用至您的個人資料圖片。",
        "NoBadgeMessage": "找不到可供您選取的徽章。請洽詢您的應用程式管理員。",
        "DigitalBadgeSubPageTitle": "以下是您的數位徽章外觀!",
        "ProfileImageAlt": "我的設定檔使用於 O365、Teams 等的影像",
        "BadgeImageAlt": "獎牌形狀獎項與字母 C 在中間表示我是擁護者計畫的一份子",
        "NoProfileImageAlt": "人員的剪影，表示目前沒有設定檔影像套用到您的帳戶",
        "ApplyButtonText": "套用影像",
        "ApplyButtonAriaDescription": "按一下此按鈕，即表示您授與擁護者計畫網頁元件許可權，以代表您更新您的個人資料圖片。",
        "ApplyButton": "套用",
        "DownloadButtonText": "下載",
        "DownloadButtonAriaDescription": "按一下以下載您目前的設定檔影像",
        "DownloadingButtonText": "正在下載...",
        "DownloadedButtonText": "已下載",
        "DownloadedButtonSecondaryText": "您可以在裝置的 [下載] 資料夾中找到您下載的設定檔影像。",
        "DownloadButtonSecondaryText": "下載您目前的設定檔影像",
        "PreApplyDisclaimer": "這是新個人資料圖片的預覽，包括數位徽章。若要在套用數位徽章前下載現有的個人資料圖片，請按一下 [<strong>下載您目前的設定檔影像</strong>] 連結。<br />",
        "PreApplyDisclaimer1": "<br />按一下 [套用影像] 將會使用此新影像更新您的 Microsoft 365 設定檔圖片。<strong>請注意，這將會更新您在所有 Microsoft 365 的個人資料圖片，而且無法透過此頁面</strong>還原 <br/><br/>如果您想要變更圖片，您可以使用 <a class='constAnchor' href='https://outlook.office365.com/owa/' target='_blank' aria-label='Open the Outlook web application in a new browser tab or window'> Outlook Web 應用程式</a>。",
        "NoProfileImageDescription": "如果您已經將圖片與您的個人資料建立關聯，但您仍然看到此訊息，您的圖片可能還無法使用。請稍後再試一次，如果 24 小時之後仍未顯示，請連絡 <a class='constAnchor' href='https://microsoft.service-now.com/' target='_blank' aria-description='Open the Outlook web application in a new browser tab or window'>服務台</a>。",
        "AcceptButtonText": "接受",
        "AcceptButtonAriaDescription": "按一下此按鈕，即表示您授與擁護者計畫網頁元件許可權，以代表您更新您的個人資料圖片。",
        "UnauthorizedText": "您目前不符合擁護者徽章計畫的資格",
        "ApplySpinnerLabel": "正在將新的設定檔影像套用至您的帳戶...",
        "DigitalBadgeSuccessMessage": "<strong>恭喜!</strong>您已成功領取您的數位徽章，且您的個人資料圖片已更新。請允許最多 24 小時查看反映在所有 Microsoft 365 應用程式的更新 (包括 Teams)。",
        "DigitalMembersToolTip": "取得您的數位徽章，並將之套用至您的個人資料影像",
        "DigitalBadgeLabel": "數位徽章",
        "AdminToolsLabel": "系統管理工具",
        "AppHeaderTitleLabel": "Teams 比賽",
        "AppLogoToolTip": "首頁",
        "MoreInfoToolTip": "其他資訊",
        "SupportToolTip": "支援",
        "FeedbackToolTip": "意見反應",
        "WelcomeLabel": "歡迎",
        "AboutHeaderLabel": "Teams 比賽",
        "AboutContentLabel": "Teams 競賽可讓整個組織擁有採用主題比賽以促進良好使用方式的遊戲資格與學習體驗。您可以在平臺中建立並傳遞比賽，以協助促進狀況的健全使用、透過執行行銷活動來提示新的學習以激勵使用者，以及追蹤和記錄活動動作，以提升事件辨識和影響。",
        "AdditionalResourcesHeaderLabel": "其他資源:",
        "AdditionalResourcesContentLabel": "Microsoft Teams 客戶參與群組著重于提供這類解決方案，以激勵並協助您達成目標。透過這些其他資源關注並加入，以深入瞭解我們與社群:",
        "M365ChampionCommunityLinkLabel": "Microsoft 365 擁護者社群",
        "DrivingAdoptionLinkLabel": "在 Microsoft 技術社群上推動採用",
        "CurrentVersionLabel": "目前版本:",
        "LatestVersionLabel": "最新版本:",
        "TOTGitHubLinkLabel": "GitHub",
        "VisitLabel": "Visit the Tournament of Teams pages to learn more:",
        "OverviewLabel": "我們的概觀與資訊",
        "MSAdoptionHubLinkLabel": "Microsoft 採用中樞",
        "DocumentationLabel": "解決方案技術檔與架構概觀:",
        "SaveButton": "儲存",
        "BackButton": "返回",
        "EnableTOTToolTip": "啟用 Teams 比賽",
        "EnableTOTLabel": "啟用 Teams 比賽",
        "CreateTournamentPageTitle": "建立比賽",
        "CreateTournamentSuccessLabel": "已成功建立比賽。",
        "TournamentNameLabel": "比賽名稱",
        "TournamentNamePlaceHolderLabel": "比賽名稱 (最多 255 個字元)",
        "TournamentNameErrorLabel": "比賽名稱是必要資訊。",
        "TournamentDescriptionLabel": "比賽說明",
        "TournamentDescPlaceHolderLabel": "比賽描述: (最多 500 個字元)",
        "SelectTeamsActionsLabel": "選取 Teams 動作:",
        "TeamsActionInfoToolTip": "從下列可用的 Teams 動作中選取要包含在新比賽中的動作。若要新增要選擇的競賽動作，請前往 [管理員工具] 中的 [管理比賽動作]。",
        "ActionErrorLabel": "請至少選取一個動作來建立比賽。",
        "CreateTournamentButton": "建立比賽",
        "DuplicateTournamentNameError": "該比賽名稱已存在。請輸入另一個比賽名稱。",
        "CreateTournamentsButton": "建立比賽",
        "SingleTournamentLabel": "單一比賽",
        "MultipleTournamentLabel": "多場比賽",
        "MultiTournamentStep": "步驟",
        "MultiTournamentStep1LinkLabel": "下載範本",
        "MultiTournamentStep1Text": "的範例檔案格式",
        "MultiTournamentStep2": "依下列指導方針將比賽詳細資料新增至檔案",
        "MultiTournamentStep3": "上傳檔案",
        "UploadFileButton": "上傳檔案",
        "RemoveFileLabel": "移除檔案",
        "ImportSpinnerMessage": "正在建立比賽.....",
        "ErrorMsgTournamentList": "在 [競賽] 清單中建立專案時發生錯誤。請更正資料，然後再試一次。",
        "ErrorMsgActionsList": "在 [動作] 清單中建立專案時發生錯誤。請更正資料，然後再試一次。",
        "ErrorMsgTournamentActionsList": "在競賽動作清單中建立專案時發生錯誤。請更正資料，然後再試一次。",
        "LogMsgTournamentExists": "已跳过，因为锦标赛已存在",
        "LogMsgTournamentExists1": "已存在。",
        "LogMsgDone": "比賽",
        "LogMsgDone1": "已建立",
        "LogMsgInvalidTournamentName": "已略過，因為它沒有有效的比賽名稱。",
        "LogMsgInvalidTemplate": "已略過，因為它不是有效的範本。",
        "LogMsgMultipleTournaments": "已略過，因為它有一個以上的比賽名稱。",
        "LogMsgBlankSheet": "已略過，因為它是空白。",
        "LogProgress": "以下是進度:",
        "ImportRule1": "請勿修改範本中的資料行標頭",
        "ImportRule2": "不要刪除範本中的欄",
        "ImportRule3": "在範本中提及的所有必要 (*) 欄位中輸入資料",
        "ImportRule4": "遵循每個欄範本中所提及的字元限制和類型",
        "ImportRule5": "根據提供的範例資料，在每張工作表中只輸入 1 個競賽的資料",
        "ImportRule6": "一次只能建立 10 場比賽",
        "ImportRule7": "請確認比賽名稱獨一無二",
        "TOTBreadcrumbLabel": "Teams 比賽",
        "EnableTOTSuccessMessage": "已成功啟用 Teams 比賽。請先重新整理應用程式再使用。",
        "TOTLeaderBoardPageTitle": "排行榜",
        "TOTMyDashboardPageTitle": "我的儀表板",
        "ManageTournamentActionsToolTip": "正在存取比賽動作清單",
        "ManageTournamentActionsLabel": "管理比賽動作",
        "ManageTournamentsLabel": "管理比賽",
        "ManageAdminsToolTip": "正在存取管理員清單",
        "ManageAdminsLabel": "管理系統管理員",
        "ManageDigitalBadgesLabel": "管理數位徽章",
        "QuickLinksLabel": "快速連結",
        "ManageTournamentsPageTitle": "管理比賽",
        "ManageToTLabel1": "一次可以開始多項比賽。請參閱下方，瞭解目前進行中的比賽、完成比賽的能力，以及開始新比賽的功能。",
        "ManageToTLabel2": "一旦比賽開始並完成之後，將無法再次開始；不過，如果您想要完成類似的比賽，可以使用相同的動作來建立新比賽!",
        "EndTournamentDialogMessage": "您確定要完成比賽嗎?",
        "StartTournamentDialogMessage": "您確定要開始新的比賽嗎?",
        "ConfirmLabel": "確認",
        "YesButton": "是",
        "NoButton": "否",
        "SearchActiveTournaments": "搜尋進行中的比賽",
        "SearchPendingTournaments": "搜尋比賽以開始",
        "SelectAllLabel": "全選",
        "NoSearchResults": "沒有符合您搜尋的結果。",
        "ActiveTournamentLabel": "進行中的比賽",
        "EndTournamentButton": "完成比賽",
        "StartTournamentHeaderLabel": "開始比賽",
        "NoTournamentMessage": "找不到任何比賽。請稍後再回來查看。",
        "SelectTournamentMessage": "至少選取一個比賽以開始。",
        "SelectEndTournamentMessage": "選取要完成的比賽。",
        "StartTournamentButton": "開始()比賽",
        "EndTournamentSuccessMessage": "已成功完成比賽。",
        "EnableTournamentSuccessMessage": "已順利開始()比賽。",
        "CompleteTournamentSpinnerMessage": "正在完成比賽...",
        "EnableTournamentSpinnerMessage": "正在啟用(比賽)...",
        "NoActiveParticipantsMessage": "目前沒有任何作用中的參與者。成為第一個從 [我的儀表板] 參與並記錄活動的人!",
        "NoActiveTournamentMessage": "目前沒有進行中的比賽。請稍後再回來查看。",
        "TournamentLabel": "比賽",
        "DescriptionLabel": "描述",
        "NoActiveParticipantsErrorMessage": "目前沒有作用中的參與者。成為第一個參與活動並從下列來源記錄活動的人 ",
        "PendingActionsLabel": "待完成動作",
        "PendingActionsSuccessMessage": "此比賽沒有其他擱置中的動作。",
        "SelectActionsErrorMessage": "請至少選取一個動作以繼續。",
        "FormSavingMessage": "正在儲存您的詳細資料。...",
        "CompletedActionsLabel": "已完成的動作",
        "RankLabel": "排名",
        "UserLabel": "使用者",
        "MyDashboardInfoIconMessage": "尋找這個動作的其他資訊",
        "SelectTournamentPlaceHolder": "選取比賽",
        "MyTournamentsLabel": "我的比賽",
        "OrLabel": "或",
        "MyTournamentsTooltip": "您已參與的進行中比賽",
        "PointsLabel": "點數",
        "TournamentRankLabel": "比賽排名",
        "ParticipantsLabel": "參與者",
        "TournamentReportsPageTitle": "比賽報告",
        "TotalActivitiesLabel": "活動總數",
        "TotalPointsLabel": "總點數",
        "TotalParticipantsLabel": "參與者總計",
        "TotalPercentageCompletionLabel": "總完成百分比的",
        "Top5ParticipantswithPointsLabel": "前 5 位有點數的參與者",
        "Top5TournamentswithParticipantsLabel": "有參與者的前 5 場比賽",
        "ParticipantsStatusLabel": "參與者狀態",
        "ParticipantsDetailsLabel": "參與者詳細資料",
        "NameLabel": "名稱",
        "PercentageTournamentCompletedLabel": "% 比賽完成",
        "ActivitiesCompletedLabel": "已完成的活動",
        "NoRecordsinGridLabel": "找不到記錄!",
        "SearchPlaceholder": "依參與者名稱搜尋",
        "NoCompletedTournamentsMessage": "目前沒有完成的比賽。請稍後再回來查看。",
        "ReportsDropdownInfoIconText": "只能為已完成的比賽產生報告。",
        "RefreshIconInfoText": "按一下 [重新整理] 以查看最新資料",
        "ProvisioningErrorMessage": "應用程式設定期間發生問題。請嘗試重新設定應用程式。",
        "ProvisioningSuccessMessage": "已成功部署 Teams 比賽。請重新整理應用程式以繼續。",
        "SpinnerMessage": "正在設定應用程式.....",
        "ProvisioningSetupMessage": "此程式需要一些時間才能完成。在您看到成功完成的訊息之前，請勿離開。"
      }

});