define([], function () {
    return {
        "PropertyPaneDescription": "说明",
        "BasicGroupName": "组名称",
        "DescriptionFieldLabel": "描述字段",
        "DigitalBadgePageTitle": "数字徽章",
        "LoadingSpinnerLabel": "正在加载…",
        "DigitalBadgeAppBannerAltText": "参与讨论的 Microsoft 团队成员",
        "PreAcceptPageTitle": "申请数字徽章!",
        "PreAcceptDisclaimer": "<span style='font-weight:bold;'>欢迎使用数字徽章实用工具</span> <br/><br/> <span>作为支持者计划的一部分，你获得了数字徽章! 此实用工具将通过将数字徽章叠加到现有个人资料图片的顶部，使你能够“<em>声明</em>”。<br/><br/> 请注意，这将更新所有 Microsoft 365 (Exchange、Teams、SharePoint 等)的个人资料图片。</span>",
        "PreAcceptDisclaimer2": "如果需要，<span style='font-weight:bold;'>你将有机会“保存”现有个人资料图片的副本</span> 后续步骤中没有数字徽章覆盖。请单击“接受”以继续(可能会看到弹出窗口打开并提示登录)。",
        "NotQualifiedPreAcceptDisclaimer": "<span style='font-weight:bold;'>欢迎使用数字徽章实用工具</span> 作为支持者计划的一部分，你可获得数字徽章! 此实用工具将通过将数字徽章叠加到现有个人资料图片的顶部，使你能够“<em>声明</em>”。请注意，这将更新所有 Microsoft 365 (Exchange、Teams、SharePoint 等)的个人资料图片。",
        "HowtoGetDigitalBadgeText": "如何获取拥护者徽章",
        "MultipleBadgeMessage": "从下面的列表中选择徽章。所选徽章将应用于你的个人资料图片。",
        "NoBadgeMessage": "找不到可供你选择的锁屏提醒。请咨询应用管理员。",
        "DigitalBadgeSubPageTitle": "下面是数字徽章的外观!",
        "ProfileImageAlt": "我的个人资料在 O365、Teams 等中使用的图像",
        "BadgeImageAlt": "中间有字母 C 的奖牌形奖，表示我是拥护者计划的一员",
        "NoProfileImageAlt": "人员的剪影，表示当前未将个人资料图像应用于你的帐户",
        "ApplyButtonText": "应用映像",
        "ApplyButtonAriaDescription": "通过单击此按钮，你将授予支持者计划 Web 部件代表你更新个人资料图片的权限。",
        "ApplyButton": "应用",
        "DownloadButtonText": "下载",
        "DownloadButtonAriaDescription": "单击以下载当前个人资料图像",
        "DownloadingButtonText": "正在下载...",
        "DownloadedButtonText": "已下载",
        "DownloadedButtonSecondaryText": "可在设备的“下载”文件夹中找到已下载的配置文件图像。",
        "DownloadButtonSecondaryText": "下载当前个人资料图像",
        "PreApplyDisclaimer": "这是新个人资料图片(包括数字徽章)的预览版。如果希望在应用数字徽章之前下载现有个人资料图片，请单击“<strong>下载当前个人资料图像</strong>”链接。<br />",
        "PreApplyDisclaimer1": "<br />单击“应用图像”将使用此新图像更新 Microsoft 365 个人资料图片。<strong>请注意，这将更新所有 Microsoft 365 的个人资料图片，并且无法通过此页面恢复</strong>。<br/><br/>如果你想要重新更改图片， 可以使用 <a class='constAnchor' href='https://outlook.office365.com/owa/' target='_blank' aria-label='在新的浏览器选项卡或窗口中打开 Outlook Web 应用程序'>Outlook Web 应用程序</a>。",
        "NoProfileImageDescription": "如果已将图片与个人资料相关联，并且仍然看到此消息，则图片可能尚不可用。请稍后重试，如果 24 小时后仍未显示，请联系 <a class='constAnchor' href='https://microsoft.service-now.com/' target='_blank' aria-description='Open the Outlook web application in a new browser tab or window'>支持人员</a>。",
        "AcceptButtonText": "接受",
        "AcceptButtonAriaDescription": "通过单击此按钮，你将授予支持者计划 Web 部件代表你更新个人资料图片的权限。",
        "UnauthorizedText": "你目前没有资格参加拥护者徽章计划",
        "ApplySpinnerLabel": "正在将新的配置文件映像应用到你的帐户...",
        "DigitalBadgeSuccessMessage": "<strong>恭喜!</strong> 你已成功申请数字徽章，并且你的个人资料图片已更新。请最多允许 24 小时查看所有 Microsoft 365 应用程序(包括 Teams)中反映的更新。",
        "DigitalMembersToolTip": "获取数字徽章并将其应用于个人资料图像",
        "DigitalBadgeLabel": "数字徽章",
        "AdminToolsLabel": "管理工具",
        "AppHeaderTitleLabel": "Teams 锦标赛",
        "AppLogoToolTip": "主页",
        "MoreInfoToolTip": "详细信息",
        "SupportToolTip": "支持",
        "FeedbackToolTip": "反馈",
        "WelcomeLabel": "欢迎",
        "AboutHeaderLabel": "Teams 锦标赛",
        "AboutContentLabel": "Teams 锦标赛可让整个组织拥有引入采用主题锦标赛的游戏和学习体验，从而促进正常使用。在平台中，你可以创建并交付锦标赛，以帮助推动方案的正常使用，通过运行活动来提示新学习来激励用户，并跟踪和记录锦标赛操作，以获得后期事件识别和影响。",
        "AdditionalResourcesHeaderLabel": "附加资源:",
        "AdditionalResourcesContentLabel": "Microsoft Teams 客户宣传组专注于提供此类解决方案，以激励和帮助你实现目标。关注并加入这些其他资源，向我们和社区了解详细信息:",
        "M365ChampionCommunityLinkLabel": "Microsoft 365 支持者社区",
        "DrivingAdoptionLinkLabel": "推动 Microsoft 技术社区采用",
        "CurrentVersionLabel": "当前版本:",
        "LatestVersionLabel": "最新版本:",
        "TOTGitHubLinkLabel": "GitHub",
        "VisitLabel": "Visit the Tournament of Teams pages to learn more:",
        "OverviewLabel": "概述和有关我们的信息",
        "MSAdoptionHubLinkLabel": "Microsoft 采用中心",
        "DocumentationLabel": "解决方案技术文档和体系结构概述",
        "SaveButton": "保存",
        "BackButton": "返回",
        "EnableTOTToolTip": "启用 Teams 锦标赛",
        "EnableTOTLabel": "启用 Teams 锦标赛",
        "CreateTournamentPageTitle": "创建锦标赛",
        "CreateTournamentSuccessLabel": "已成功创建锦标赛。",
        "TournamentNameLabel": "锦标赛名称",
        "TournamentNamePlaceHolderLabel": "锦标赛名称(最多 255 个字符)",
        "TournamentNameErrorLabel": "锦标赛名称是必需的。",
        "TournamentDescriptionLabel": "锦标赛说明",
        "TournamentDescPlaceHolderLabel": "锦标赛说明(最多 500 个字符)",
        "SelectTeamsActionsLabel": "选择 Teams 操作:",
        "TeamsActionInfoToolTip": "从以下可用 Teams 操作中进行选择，以包含在新锦标赛中。若要添加要选择的新锦标赛操作，请访问管理工具中的“管理锦标赛操作”。",
        "ActionErrorLabel": "选择至少一个操作以创建锦标赛。",
        "CreateTournamentButton": "创建锦标赛",
        "DuplicateTournamentNameError": "锦标赛名称已存在。请为锦标赛输入另一个名称。",
        "CreateTournamentsButton": "创建锦标赛",
        "SingleTournamentLabel": "单个锦标赛",
        "MultipleTournamentLabel": "多个锦标赛",
        "MultiTournamentStep": "步骤",
        "MultiTournamentStep1LinkLabel": "下载模板",
        "MultiTournamentStep1Text": "示例文件格式",
        "MultiTournamentStep2": "按照以下准则将锦标赛详细信息添加到文件",
        "MultiTournamentStep3": "上载文件",
        "UploadFileButton": "上传文件",
        "RemoveFileLabel": "删除文件",
        "ImportSpinnerMessage": "正在创建锦标赛......",
        "ErrorMsgTournamentList": "在“锦标赛”列表中创建项目时出错。请更正数据，然后重试。",
        "ErrorMsgActionsList": "在“操作”列表中创建项时出错。请更正数据，然后重试。",
        "ErrorMsgTournamentActionsList": "在锦标赛操作列表中创建项目时出错。请更正数据，然后重试。",
        "LogMsgTournamentExists": "已略過，因為比賽",
        "LogMsgTournamentExists1": "已經存在。",
        "LogMsgDone": "锦标赛",
        "LogMsgDone1": "已创建",
        "LogMsgInvalidTournamentName": "已跳过，因为它没有有效的锦标赛名称。",
        "LogMsgInvalidTemplate": "已跳过，因为它不是有效的模板。",
        "LogMsgMultipleTournaments": "已跳过，因为它具有多个锦标赛名称。",
        "LogMsgBlankSheet": "已跳过，因为它为空。",
        "LogProgress": "下面是进度:",
        "ImportRule1": "不修改模板中的列标题",
        "ImportRule2": "不要删除模板中的列",
        "ImportRule3": "在模板中提到的所有必需(*)列中输入数据",
        "ImportRule4": "遵循每个列的模板中提到的字符限制和类型",
        "ImportRule5": "根据提供的示例数据，在每个工作表中仅输入 1 个锦标赛的数据",
        "ImportRule6": "一次只能创建 10 个锦标赛",
        "ImportRule7": "确保锦标赛名称是唯一的",
        "TOTBreadcrumbLabel": "Teams 锦标赛",
        "EnableTOTSuccessMessage": "已成功启用 Teams 锦标赛。请在使用前刷新应用。",
        "TOTLeaderBoardPageTitle": "排行榜",
        "TOTMyDashboardPageTitle": "我的仪表板",
        "ManageTournamentActionsToolTip": "访问锦标赛操作列表",
        "ManageTournamentActionsLabel": "管理锦标赛操作",
        "ManageTournamentsLabel": "管理锦标赛",
        "ManageAdminsToolTip": "访问管理员列表",
        "ManageAdminsLabel": "管理管理员",
        "ManageDigitalBadgesLabel": "管理数字徽章",
        "QuickLinksLabel": "快速链接",
        "ManageTournamentsPageTitle": "管理锦标赛",
        "ManageToTLabel1": "一次可以启动多个锦标赛。请参阅以下内容，了解当前活动锦标赛、完成锦标赛的能力以及启动新锦标赛的功能。",
        "ManageToTLabel2": "锦标赛启动并完成后，将无法重新开始;但是，如果要完成类似的锦标赛，可以使用相同的操作创建新锦标赛!",
        "EndTournamentDialogMessage": "是否确定要完成锦标赛?",
        "StartTournamentDialogMessage": "是否确定要开始新锦标赛?",
        "ConfirmLabel": "确认",
        "YesButton": "是",
        "NoButton": "否",
        "SearchActiveTournaments": "搜索活动锦标赛",
        "SearchPendingTournaments": "搜索锦标赛以开始",
        "SelectAllLabel": "全选",
        "NoSearchResults": "没有与搜索匹配的结果。",
        "ActiveTournamentLabel": "活跃的锦标赛",
        "EndTournamentButton": "完成锦标赛",
        "StartTournamentHeaderLabel": "开始锦标赛",
        "NoTournamentMessage": "未找到锦标赛。请稍后再试。",
        "SelectTournamentMessage": "至少选择一个锦标赛以开始。",
        "SelectEndTournamentMessage": "选择要完成的锦标赛。",
        "StartTournamentButton": "开始锦标赛(的)",
        "EndTournamentSuccessMessage": "锦标赛已成功完成。",
        "EnableTournamentSuccessMessage": "锦标赛(的)已成功开始。",
        "CompleteTournamentSpinnerMessage": "正在完成锦标赛...",
        "EnableTournamentSpinnerMessage": "正在启用锦标赛(的)...",
        "NoActiveParticipantsMessage": "目前没有活动参与者。成为第一个从“我的仪表板”参与和记录活动的人!",
        "NoActiveTournamentMessage": "当前没有活动的锦标赛。请稍后返回查看。",
        "TournamentLabel": "锦标赛",
        "DescriptionLabel": "说明",
        "NoActiveParticipantsErrorMessage": "目前没有活动参与者。成为第一个参与和记录活动的人",
        "PendingActionsLabel": "挂起的操作",
        "PendingActionsSuccessMessage": "此锦标赛中没有其他挂起的操作。",
        "SelectActionsErrorMessage": "至少选择一个操作以继续。",
        "FormSavingMessage": "正在保存你的详细信息......",
        "CompletedActionsLabel": "已完成的操作",
        "RankLabel": "排序",
        "UserLabel": "用户",
        "MyDashboardInfoIconMessage": "了解有关此操作的详细信息",
        "SelectTournamentPlaceHolder": "选择锦标赛",
        "MyTournamentsLabel": "我的锦标赛",
        "OrLabel": "或",
        "MyTournamentsTooltip": "你已参与的活动锦标赛",
        "PointsLabel": "得分",
        "TournamentRankLabel": "锦标赛排名",
        "ParticipantsLabel": "参与者",
        "TournamentReportsPageTitle": "锦标赛报告",
        "TotalActivitiesLabel": "总活动",
        "TotalPointsLabel": "总得分",
        "TotalParticipantsLabel": "参与者总计",
        "TotalPercentageCompletionLabel": "完成总量的百分比",
        "Top5ParticipantswithPointsLabel": "分数排名前 5 的参与者",
        "Top5TournamentswithParticipantsLabel": "与参与者一起参加的前 5 项锦标赛",
        "ParticipantsStatusLabel": "参与者状态",
        "ParticipantsDetailsLabel": "参与者详细信息",
        "NameLabel": "名称",
        "PercentageTournamentCompletedLabel": "锦标赛已完成百分比",
        "ActivitiesCompletedLabel": "活动已完成",
        "NoRecordsinGridLabel": "找不到记录!",
        "SearchPlaceholder": "按参与者姓名搜索",
        "NoCompletedTournamentsMessage": "目前没有已完成的锦标赛。请稍后返回查看。",
        "ReportsDropdownInfoIconText": "只能为已完成的锦标赛生成报告。",
        "RefreshIconInfoText": "单击“刷新”以查看最新数据",
        "ProvisioningErrorMessage": "在应用安装过程中出现问题。请尝试重新设置应用。",
        "ProvisioningSuccessMessage": "已成功部署 Teams 锦标赛。请刷新应用以继续。",
        "SpinnerMessage": "正在设置应用.....",
        "ProvisioningSetupMessage": "此过程需要一些时间才能完成。在看到成功完成的消息之前，请不要离开。"
      }

});